### ISSUE TITLE
Directory data/graphs/car does not exist and cannot be created to place lock file there: data/graphs/car/gh.lock 	at com.graphhopper.storage.NativeFSLockFactory$NativeLock.tryLock(NativeFSLockFactory.java:110) ~[graphhopper-core-v0.13.15.jar:?] 	at com.graphhopper.GraphHopper.

### ISSUE THREAD

**Issue by vinaypuranik** [GIScience/openrouteservice#1060]
Trying to run the docker image but getting this error.  Any idea on how to resolve this ?
```  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v2.3.5.RELEASE)
17 Sep 14:01:08 INFO [ors.Application] - Starting Application v6.6.1 on ors-app-6f6fc79dbc-tx9sf with PID 85 (/usr/local/tomcat/webapps/ors/WEB-INF/classes started by ors in /ors-core)
17 Sep 14:01:08 DEBUG [ors.Application] - Running with Spring Boot v2.3.5.RELEASE, Spring v5.2.10.RELEASE
17 Sep 14:01:08 INFO [ors.Application] - No active profile set, falling back to default profiles: default
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
17 Sep 14:01:10 INFO [ors.Application] - Started Application in 3.562 seconds (JVM running for 9.002)
17-Sep-2021 14:01:10.993 INFO [localhost-startStop-1] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
<?xml version="1.0" ?>
<Configuration>
  <Properties>
    <Property name="filename">/var/log/ors/ors-logs.log
  </Properties>
</Configuration>
17 Sep 14:01:11 INFO [routing.RoutingProfileManager] -  Total - 2.00 GB, Free - 1.78 GB, Max: 4 GB, Used - 229.39 MB
17 Sep 14:01:11 INFO [routing.RoutingProfileManager] -       
17-Sep-2021 14:01:11.048 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Deployment of web application archive [/usr/local/tomcat/webapps/ors.war] has finished in [8,403] ms
17-Sep-2021 14:01:11.052 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory [/usr/local/tomcat/webapps/examples]
17 Sep 14:01:11 INFO [routing.RoutingProfileManager] - ====> Initializing profiles from 'data/osm_file.pbf' (1 threads) ...
17 Sep 14:01:11 INFO [routing.RoutingProfileManager] -                               
17 Sep 14:01:11 INFO [routing.RoutingProfileManager] -                
17 Sep 14:01:11 INFO [routing.RoutingProfile] - [1] Profiles: 'driving-car', location: 'data/graphs/car'.
17-Sep-2021 14:01:11.204 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [/usr/local/tomcat/webapps/examples] has finished in [152] ms
17-Sep-2021 14:01:11.205 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory [/usr/local/tomcat/webapps/host-manager]
17-Sep-2021 14:01:11.222 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [/usr/local/tomcat/webapps/host-manager] has finished in [17] ms
17-Sep-2021 14:01:11.223 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory [/usr/local/tomcat/webapps/docs]
17-Sep-2021 14:01:11.233 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [/usr/local/tomcat/webapps/docs] has finished in [10] ms
17-Sep-2021 14:01:11.234 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory [/usr/local/tomcat/webapps/ROOT]
17-Sep-2021 14:01:11.243 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [/usr/local/tomcat/webapps/ROOT] has finished in [10] ms
17-Sep-2021 14:01:11.244 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory [/usr/local/tomcat/webapps/manager]
17-Sep-2021 14:01:11.265 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [/usr/local/tomcat/webapps/manager] has finished in [21] ms
17-Sep-2021 14:01:11.274 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-nio-8080"]
17-Sep-2021 14:01:11.285 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["ajp-nio-8009"]
17-Sep-2021 14:01:11.295 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in 8716 ms
17 Sep 14:01:11 ERROR [routing.RoutingProfileManager] - java.util.concurrent.ExecutionException: java.lang.RuntimeException: Directory data/graphs/car does not exist and cannot be created to place lock file there: data/graphs/car/gh.lock
17 Sep 14:01:11 ERROR [routing.RoutingProfileManager] - Failed to initialize RoutingProfileManager instance.
java.util.concurrent.ExecutionException: java.lang.RuntimeException: Directory data/graphs/car does not exist and cannot be created to place lock file there: data/graphs/car/gh.lock
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:?]
	at java.util.concurrent.FutureTask.get(FutureTask.java:191) ~[?:?]
	at org.heigit.ors.routing.RoutingProfileManager.initialize(RoutingProfileManager.java:176) ~[classes/:6.6.1]
	at org.heigit.ors.routing.RoutingProfileManager.getInstance(RoutingProfileManager.java:70) ~[classes/:6.6.1]
	at org.heigit.ors.servlet.listeners.ORSInitContextListener.lambda$contextInitialized$0(ORSInitContextListener.java:41) ~[classes/:6.6.1]
	at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: java.lang.RuntimeException: Directory data/graphs/car does not exist and cannot be created to place lock file there: data/graphs/car/gh.lock
	at com.graphhopper.storage.NativeFSLockFactory$NativeLock.tryLock(NativeFSLockFactory.java:110) ~[graphhopper-core-v0.13.15.jar:?]
	at com.graphhopper.GraphHopper.process(GraphHopper.java:697) ~[graphhopper-core-v0.13.15.jar:?]
	at com.graphhopper.GraphHopper.importOrLoad(GraphHopper.java:680) ~[graphhopper-core-v0.13.15.jar:?]
	at org.heigit.ors.routing.graphhopper.extensions.ORSGraphHopper.importOrLoad(ORSGraphHopper.java:155) ~[classes/:6.6.1]
	at org.heigit.ors.routing.RoutingProfile.initGraphHopper(RoutingProfile.java:189) ~[classes/:6.6.1]
	at org.heigit.ors.routing.RoutingProfile.<init>(RoutingProfile.java:133) ~[classes/:6.6.1]
	at org.heigit.ors.routing.RoutingProfileLoader.call(RoutingProfileLoader.java:35) ~[classes/:6.6.1]
	at org.heigit.ors.routing.RoutingProfileLoader.call(RoutingProfileLoader.java:21) ~[classes/:6.6.1]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	... 1 more
17 Sep 14:01:11 INFO [routing.RoutingProfileManager] - ====> Recycling garbage...
17 Sep 14:01:11 INFO [routing.RoutingProfileManager] - Before:  Total - 2.00 GB, Free - 1.71 GB, Max: 4 GB, Used - 299.89 MB
17 Sep 14:01:11 INFO [routing.RoutingProfileManager] - After:  Total - 2 GB, Free - 1.97 GB, Max: 4 GB, Used - 32.06 MB
17 Sep 14:01:11 INFO [routing.RoutingProfileManager] - ========================================================================
17 Sep 14:01:11 INFO [routing.RoutingProfileManager] - ====> Memory usage by profiles:
17 Sep 14:01:11 INFO [routing.RoutingProfileManager] - Total: 0 B (0.0%)
17 Sep 14:01:11 INFO [routing.RoutingProfileManager] - ========================================================================
```

**Comment by TheGreatRefrigerator** [comment]
> Caused by: java.lang.RuntimeException: Directory data/graphs/car does not exist and cannot be created to place lock file there: data/graphs/car/gh.lock

probably a permission error with the docker volume.
Is the mapped path existing on the machine your running the image on and does docker have writing permission to the specified folder?

**Comment by vinaypuranik** [comment]
Ok..  No longer facing this error, we can mark this issue as closed.

**Comment by TheGreatRefrigerator** [comment]
Thanks for reporting back!
Could you add a small comment, with what resolved the issue, please?

**Comment by marisancans** [comment]
I hate when people dont add solution. I had this problem too and you have to manually create the folders before starting the docker.
From documentation: mkdir -p conf elevation_cache graphs logs/ors logs/tomcat

If you are using docker-compose, make sure your volume mounts are the same. This error is caused when docker-compose created the folders not you.
