### ISSUE TITLE
Investigate GTFSStorage files not closing properly

### ISSUE THREAD

**Issue by takb** [GIScience/openrouteservice#1209]
on the gh-4.0-gtfs branch, at least one of the files used by GTFSStorage is not closed properly sometimes. We should look into wether this file needs to be kept open at runtime and if so if we can find a way to close the file properly in case ORS is stopped suddenly.
```2022-09-01 10:07:05,711 INFO [ors.Application] - Starting Application v6.7.0-gtfs on 6a88bf1249fd with PID 12 (/opt/apache-tomcat-8.5.69/webapps/ors/WEB-INF/classes started by root in /)
2022-09-01 10:07:05,713 DEBUG [ors.Application] - Running with Spring Boot v2.3.5.RELEASE, Spring v5.2.10.RELEASE
2022-09-01 10:07:05,714 INFO [ors.Application] - No active profile set, falling back to default profiles: default
2022-09-01 10:07:07,830 INFO [ors.Application] - Started Application in 2.861 seconds (JVM running for 8.638)
2022-09-01 10:07:07,848 INFO [logging.LoggingUtility] - Logging configuration loaded from DEBUG_LOGGING.json, logging to file /opt/ors/logs/ors/ors-logs.log
2022-09-01 10:07:07,857 INFO [routing.RoutingProfileManager] -  Total - 120 GB, Free - 119.12 GB, Max: 120 GB, Used - 905.96 MB
2022-09-01 10:07:07,858 INFO [routing.RoutingProfileManager] -
2022-09-01 10:07:07,885 INFO [routing.RoutingProfileManager] - ====> Initializing profiles from '/opt/ors/osm/osm_file.osm.pbf' (1 threads) ...
2022-09-01 10:07:07,886 INFO [routing.RoutingProfileManager] - 1 tasks submitted.
2022-09-01 10:07:07,904 INFO [routing.RoutingProfile] - [1] Profiles: 'pt', location: '/opt/ors/graphs/pt'.
2022-09-01 10:07:09,698 ERROR [routing.RoutingProfileManager] - java.util.concurrent.ExecutionException: java.io.IOError: java.io.IOException: Wrong index checksum, store was not closed properly and could be corrupted.
2022-09-01 10:07:09,698 ERROR [routing.RoutingProfileManager] - Failed to initialize RoutingProfileManager instance.
java.util.concurrent.ExecutionException: java.io.IOError: java.io.IOException: Wrong index checksum, store was not closed properly and could be corrupted.
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:?]
	at java.util.concurrent.FutureTask.get(FutureTask.java:191) ~[?:?]
	at org.heigit.ors.routing.RoutingProfileManager.initialize(RoutingProfileManager.java:178) ~[classes/:6.7.0-gtfs]
	at org.heigit.ors.routing.RoutingProfileManager.getInstance(RoutingProfileManager.java:72) ~[classes/:6.7.0-gtfs]
	at org.heigit.ors.servlet.listeners.ORSInitContextListener.lambda$contextInitialized$0(ORSInitContextListener.java:42) ~[classes/:6.7.0-gtfs]
	at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: java.io.IOError: java.io.IOException: Wrong index checksum, store was not closed properly and could be corrupted.
	at org.mapdb.StoreDirect.checkHeaders(StoreDirect.java:269) ~[mapdb-1.0.8.jar:?]
	at org.mapdb.StoreDirect.<init>(StoreDirect.java:207) ~[mapdb-1.0.8.jar:?]
	at org.mapdb.DBMaker.extendStoreDirect(DBMaker.java:971) ~[mapdb-1.0.8.jar:?]
	at org.mapdb.DBMaker.makeEngine(DBMaker.java:758) ~[mapdb-1.0.8.jar:?]
	at org.mapdb.DBMaker.make(DBMaker.java:701) ~[mapdb-1.0.8.jar:?]
	at com.graphhopper.gtfs.GtfsStorage.loadExisting(GtfsStorage.java:161) ~[graphhopper-reader-gtfs-gtfs-4.0.3.jar:?]
	at com.graphhopper.gtfs.GraphHopperGtfs.importPublicTransit(GraphHopperGtfs.java:80) ~[graphhopper-reader-gtfs-gtfs-4.0.3.jar:?]
	at com.graphhopper.GraphHopper.postProcessing(GraphHopper.java:1037) ~[graphhopper-core-gtfs-4.0.3.jar:?]
	at com.graphhopper.GraphHopper.load(GraphHopper.java:879) ~[graphhopper-core-gtfs-4.0.3.jar:?]
	at com.graphhopper.GraphHopper.importOrLoad(GraphHopper.java:676) ~[graphhopper-core-gtfs-4.0.3.jar:?]
	at org.heigit.ors.routing.graphhopper.extensions.ORSGraphHopper.importOrLoad(ORSGraphHopper.java:171) ~[classes/:6.7.0-gtfs]
	at org.heigit.ors.routing.RoutingProfile.initGraphHopper(RoutingProfile.java:192) ~[classes/:6.7.0-gtfs]
	at org.heigit.ors.routing.RoutingProfile.<init>(RoutingProfile.java:139) ~[classes/:6.7.0-gtfs]
	at org.heigit.ors.routing.RoutingProfileLoader.call(RoutingProfileLoader.java:39) ~[classes/:6.7.0-gtfs]
	at org.heigit.ors.routing.RoutingProfileLoader.call(RoutingProfileLoader.java:25) ~[classes/:6.7.0-gtfs]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	... 1 more
Caused by: java.io.IOException: Wrong index checksum, store was not closed properly and could be corrupted.
	at org.mapdb.StoreDirect.checkHeaders(StoreDirect.java:269) ~[mapdb-1.0.8.jar:?]
	at org.mapdb.StoreDirect.<init>(StoreDirect.java:207) ~[mapdb-1.0.8.jar:?]
	at org.mapdb.DBMaker.extendStoreDirect(DBMaker.java:971) ~[mapdb-1.0.8.jar:?]
	at org.mapdb.DBMaker.makeEngine(DBMaker.java:758) ~[mapdb-1.0.8.jar:?]
	at org.mapdb.DBMaker.make(DBMaker.java:701) ~[mapdb-1.0.8.jar:?]
	at com.graphhopper.gtfs.GtfsStorage.loadExisting(GtfsStorage.java:161) ~[graphhopper-reader-gtfs-gtfs-4.0.3.jar:?]
	at com.graphhopper.gtfs.GraphHopperGtfs.importPublicTransit(GraphHopperGtfs.java:80) ~[graphhopper-reader-gtfs-gtfs-4.0.3.jar:?]
	at com.graphhopper.GraphHopper.postProcessing(GraphHopper.java:1037) ~[graphhopper-core-gtfs-4.0.3.jar:?]
	at com.graphhopper.GraphHopper.load(GraphHopper.java:879) ~[graphhopper-core-gtfs-4.0.3.jar:?]
	at com.graphhopper.GraphHopper.importOrLoad(GraphHopper.java:676) ~[graphhopper-core-gtfs-4.0.3.jar:?]
	at org.heigit.ors.routing.graphhopper.extensions.ORSGraphHopper.importOrLoad(ORSGraphHopper.java:171) ~[classes/:6.7.0-gtfs]
	at org.heigit.ors.routing.RoutingProfile.initGraphHopper(RoutingProfile.java:192) ~[classes/:6.7.0-gtfs]
	at org.heigit.ors.routing.RoutingProfile.<init>(RoutingProfile.java:139) ~[classes/:6.7.0-gtfs]
	at org.heigit.ors.routing.RoutingProfileLoader.call(RoutingProfileLoader.java:39) ~[classes/:6.7.0-gtfs]
	at org.heigit.ors.routing.RoutingProfileLoader.call(RoutingProfileLoader.java:25) ~[classes/:6.7.0-gtfs]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
	... 1 more
2022-09-01 10:07:09,708 INFO [routing.RoutingProfileManager] - ====> Recycling garbage...
2022-09-01 10:07:09,708 INFO [routing.RoutingProfileManager] - Before:  Total - 120 GB, Free - 118.30 GB, Max: 120 GB, Used - 1.70 GB
2022-09-01 10:07:09,824 INFO [routing.RoutingProfileManager] - After:  Total - 120 GB, Free - 119.94 GB, Max: 120 GB, Used - 57.86 MB
2022-09-01 10:07:09,824 INFO [routing.RoutingProfileManager] - ========================================================================
2022-09-01 10:07:09,824 INFO [routing.RoutingProfileManager] - ====> Memory usage by profiles:
2022-09-01 10:07:09,825 INFO [routing.RoutingProfileManager] - Total: 0 B (0.0%)
2022-09-01 10:07:09,825 INFO [routing.RoutingProfileManager] - ========================================================================```

Needs to be looked into before we think about merging the GTFS feature branch.

**Comment by MichaelsJP** [comment]
Connected to #1325
