### ISSUE TITLE
RoutingProfileManager exits with NullPointerException when using app.config.sample

### ISSUE THREAD

**Issue by sfendrich** [GIScience/openrouteservice#425]
#### Here's what I did

`cp app.config.sample app.config` and adapt app.config to local paths

```
mvn clean package
mvn tomcat7:run
```

---
#### Here's what I got

```
28 Feb 10:16:19 ERROR [routing.RoutingProfileManager] - Failed to initialize RoutingProfileManager instance.
java.lang.NullPointerException: null
	at heigit.ors.routing.configuration.RoutingManagerConfiguration.loadFromFile(RoutingManagerConfiguration.java:50) ~[RoutingManagerConfiguration.class:?]
	at heigit.ors.routing.RoutingProfileManager.initialize(RoutingProfileManager.java:176) ~[RoutingProfileManager.class:?]
	at heigit.ors.routing.RoutingProfileManager.getInstance(RoutingProfileManager.java:72) ~[RoutingProfileManager.class:?]
	at heigit.ors.servlet.listeners.ORSInitContextListener.lambda$contextInitialized$0(ORSInitContextListener.java:43) ~[ORSInitContextListener.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
```

---
#### Here's what I was expecting
app.config.sample should work with minimal changes to local environment.

**Comment by sfendrich** [comment]
The failure happens because no active routing profiles are configured in app.config.sample. This may be resolved by uncommenting the line "active: [...]" in section "routing". This is an acceptable minimal change as long it is documented.
Leaving the profiles deactivated may be a sensible default, if we want to prevent building lots of graphs accidentally. However, RoutingProfileManager should stop with a sensible error message (e.g., "No active profiles in app.config.") instead of a NullPointerException.

**Comment by sfendrich** [comment]
RoutingProfileManager is so messy that it makes no sense to fix this minor issue without fixing the more severe ones. Therefore, this issue will be fixed when cleaning up RoutingProfileManager.
