### ISSUE TITLE
Error when running the project in intelij

### ISSUE THREAD

**Issue by ifle** [GIScience/openrouteservice#545]
Hi,

I try to run the ORS in intelij on WIN 10 and have this error. What is missing?
```java

org.springframework.beans.factory.BeanDefinitionStoreException: Failed to parse configuration class [heigit.ors.Application]; nested exception is java.lang.IllegalStateException: Failed to introspect annotated methods on class org.springframework.boot.web.servlet.support.SpringBootServletInitializer
	at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:184) ~[spring-context-5.0.8.RELEASE.jar:5.0.8.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:316) ~[spring-context-5.0.8.RELEASE.jar:5.0.8.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:233) ~[spring-context-5.0.8.RELEASE.jar:5.0.8.RELEASE]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:271) ~[spring-context-5.0.8.RELEASE.jar:5.0.8.RELEASE]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:91) ~[spring-context-5.0.8.RELEASE.jar:5.0.8.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:694) ~[spring-context-5.0.8.RELEASE.jar:5.0.8.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:532) ~[spring-context-5.0.8.RELEASE.jar:5.0.8.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:762) [spring-boot-2.0.4.RELEASE.jar:2.0.4.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:398) [spring-boot-2.0.4.RELEASE.jar:2.0.4.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:330) [spring-boot-2.0.4.RELEASE.jar:2.0.4.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1258) [spring-boot-2.0.4.RELEASE.jar:2.0.4.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1246) [spring-boot-2.0.4.RELEASE.jar:2.0.4.RELEASE]
	at heigit.ors.Application.main(Application.java:12) [classes/:?]
Caused by: java.lang.IllegalStateException: Failed to introspect annotated methods on class org.springframework.boot.web.servlet.support.SpringBootServletInitializer
	at org.springframework.core.type.StandardAnnotationMetadata.getAnnotatedMethods(StandardAnnotationMetadata.java:169) ~[spring-core-5.0.8.RELEASE.jar:5.0.8.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassParser.retrieveBeanMethodMetadata(ConfigurationClassParser.java:393) ~[spring-context-5.0.8.RELEASE.jar:5.0.8.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassParser.doProcessConfigurationClass(ConfigurationClassParser.java:318) ~[spring-context-5.0.8.RELEASE.jar:5.0.8.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassParser.processConfigurationClass(ConfigurationClassParser.java:245) ~[spring-context-5.0.8.RELEASE.jar:5.0.8.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:202) ~[spring-context-5.0.8.RELEASE.jar:5.0.8.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:170) ~[spring-context-5.0.8.RELEASE.jar:5.0.8.RELEASE]
	... 12 more
Caused by: java.lang.NoClassDefFoundError: javax/servlet/ServletContext
	at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:1.8.0_181]
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701) ~[?:1.8.0_181]
	at java.lang.Class.getDeclaredMethods(Class.java:1975) ~[?:1.8.0_181]
	at org.springframework.core.type.StandardAnnotationMetadata.getAnnotatedMethods(StandardAnnotationMetadata.java:158) ~[spring-core-5.0.8.RELEASE.jar:5.0.8.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassParser.retrieveBeanMethodMetadata(ConfigurationClassParser.java:393) ~[spring-context-5.0.8.RELEASE.jar:5.0.8.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassParser.doProcessConfigurationClass(ConfigurationClassParser.java:318) ~[spring-context-5.0.8.RELEASE.jar:5.0.8.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassParser.processConfigurationClass(ConfigurationClassParser.java:245) ~[spring-context-5.0.8.RELEASE.jar:5.0.8.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:202) ~[spring-context-5.0.8.RELEASE.jar:5.0.8.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:170) ~[spring-context-5.0.8.RELEASE.jar:5.0.8.RELEASE]
	... 12 more
Caused by: java.lang.ClassNotFoundException: javax.servlet.ServletContext
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_181]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_181]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349) ~[?:1.8.0_181]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_181]
	at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:1.8.0_181]
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701) ~[?:1.8.0_181]
	at java.lang.Class.getDeclaredMethods(Class.java:1975) ~[?:1.8.0_181]
	at org.springframework.core.type.StandardAnnotationMetadata.getAnnotatedMethods(StandardAnnotationMetadata.java:158) ~[spring-core-5.0.8.RELEASE.jar:5.0.8.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassParser.retrieveBeanMethodMetadata(ConfigurationClassParser.java:393) ~[spring-context-5.0.8.RELEASE.jar:5.0.8.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassParser.doProcessConfigurationClass(ConfigurationClassParser.java:318) ~[spring-context-5.0.8.RELEASE.jar:5.0.8.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassParser.processConfigurationClass(ConfigurationClassParser.java:245) ~[spring-context-5.0.8.RELEASE.jar:5.0.8.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:202) ~[spring-context-5.0.8.RELEASE.jar:5.0.8.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:170) ~[spring-context-5.0.8.RELEASE.jar:5.0.8.RELEASE]

```

**Comment by rabidllama** [comment]
How are you trying to run it? If you intend to run it directly from within IntelliJ, using a Maven Run configuration with `clean package tomcat7:run` normally works.
Otherwise, you would need to build the WAR file and then drop it into your Tomcat webapps folder on your system.

**Comment by ifle** [comment]
@rabidllama Thanks for your advice. Using a Maven Run works. But during loading I still have error
The matrix service return the "Matrix service is not ready yet" message. 
```java
12 Jun 17:59:03 INFO [routing.RoutingProfileManager] - [1] Profiles: 'driving-hgv', location: 'graphs\hgv'.
12 Jun 17:59:03 INFO [routing.RoutingProfileManager] - [2] Profiles: 'driving-car', location: 'graphs\car'.
12 Jun 17:59:13 ERROR [routing.RoutingProfileManager] - java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.NullPointerException
12 Jun 17:59:13 INFO [routing.RoutingProfileManager] - [3] Profiles: 'cycling-regular', location: 'graphs\bike-regular'.
java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.NullPointerException
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:192)
        at heigit.ors.routing.RoutingProfileManager.initialize(RoutingProfileManager.java:216)
        at heigit.ors.routing.RoutingProfileManager.getInstance(RoutingProfileManager.java:64)
        at heigit.ors.servlet.listeners.ORSInitContextListener.lambda$contextInitialized$0(ORSInitContextListener.java:43)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.NullPointerException
        at heigit.ors.routing.graphhopper.extensions.core.CoreLMAlgoFactoryDecorator.loadOrDoWork(CoreLMAlgoFactoryDecorator.java:278)
        at heigit.ors.routing.graphhopper.extensions.ORSGraphHopper.loadOrPrepareCoreLM(ORSGraphHopper.java:623)
        at heigit.ors.routing.graphhopper.extensions.ORSGraphHopper.postProcessing(ORSGraphHopper.java:539)
        at com.graphhopper.GraphHopper.process(GraphHopper.java:719)
        at com.graphhopper.GraphHopper.importOrLoad(GraphHopper.java:688)
        at heigit.ors.routing.graphhopper.extensions.ORSGraphHopper.importOrLoad(ORSGraphHopper.java:156)
        at heigit.ors.routing.RoutingProfile.initGraphHopper(RoutingProfile.java:158)
        at heigit.ors.routing.RoutingProfile.<init>(RoutingProfile.java:103)
        at heigit.ors.routing.RoutingProfileLoader.call(RoutingProfileLoader.java:37)
        at heigit.ors.routing.RoutingProfileLoader.call(RoutingProfileLoader.java:21)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        ... 1 more
Caused by: java.util.concurrent.ExecutionException: java.lang.NullPointerException
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:192)
        at heigit.ors.routing.graphhopper.extensions.core.CoreLMAlgoFactoryDecorator.loadOrDoWork(CoreLMAlgoFactoryDecorator.java:274)
        ... 15 more
Caused by: java.lang.NullPointerException
        at heigit.ors.routing.graphhopper.extensions.edgefilters.core.AvoidBordersCoreEdgeFilter.restrictedCountry(AvoidBordersCoreEdgeFilter.java:64)
        at heigit.ors.routing.graphhopper.extensions.edgefilters.core.AvoidBordersCoreEdgeFilter.accept(AvoidBordersCoreEdgeFilter.java:53)
        at heigit.ors.routing.graphhopper.extensions.edgefilters.EdgeFilterSequence.accept(EdgeFilterSequence.java:28)
        at heigit.ors.routing.graphhopper.extensions.edgefilters.EdgeFilterSequence.accept(EdgeFilterSequence.java:28)
        at com.graphhopper.storage.BaseGraph$EdgeIterable.next(BaseGraph.java:979)
        at heigit.ors.routing.graphhopper.extensions.core.TarjansCoreSCCAlgorithm.strongConnect(TarjansCoreSCCAlgorithm.java:152)
        at heigit.ors.routing.graphhopper.extensions.core.TarjansCoreSCCAlgorithm.findComponents(TarjansCoreSCCAlgorithm.java:108)
        at heigit.ors.routing.graphhopper.extensions.core.CoreLandmarkStorage.createLandmarks(CoreLandmarkStorage.java:251)
        at heigit.ors.routing.graphhopper.extensions.core.PrepareCoreLandmarks.doWork(PrepareCoreLandmarks.java:134)
        at heigit.ors.routing.graphhopper.extensions.core.CoreLMAlgoFactoryDecorator$1.run(CoreLMAlgoFactoryDecorator.java:264)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        ... 6 more
12 Jun 17:59:13 INFO [routing.RoutingProfileManager] - [3] FlagEncoders: 1, bits used [UNKNOWN]/64.
12 Jun 17:59:13 INFO [routing.RoutingProfileManager] - [3] Capacity: [UNKNOWN]. (edges - 39664, nodes - 28778)
12 Jun 17:59:13 INFO [routing.RoutingProfileManager] - [3] Total time: 0.087s.
12 Jun 17:59:13 INFO [routing.RoutingProfileManager] - [3] Finished at: 2019-06-12 17:59:13.
12 Jun 17:59:13 INFO [routing.RoutingProfileManager] -
12 Jun 17:59:13 INFO [routing.RoutingProfileManager] - [4] Profiles: 'cycling-mountain', location: 'graphs\bike-mountain'.
12 Jun 17:59:13 INFO [routing.RoutingProfileManager] - [4] FlagEncoders: 1, bits used [UNKNOWN]/64.
12 Jun 17:59:13 INFO [routing.RoutingProfileManager] - [4] Capacity: [UNKNOWN]. (edges - 39704, nodes - 28803)
12 Jun 17:59:13 INFO [routing.RoutingProfileManager] - [4] Total time: 0.059s.
12 Jun 17:59:13 INFO [routing.RoutingProfileManager] - [4] Finished at: 2019-06-12 17:59:13.
12 Jun 17:59:13 INFO [routing.RoutingProfileManager] -
12 Jun 17:59:13 INFO [routing.RoutingProfileManager] - [5] Profiles: 'cycling-road', location: 'graphs\bike-road'.
12 Jun 17:59:13 INFO [bike.CommonBikeFlagEncoder] - NextGen RoadBike FlagEncoder is active...
12 Jun 17:59:13 ERROR [routing.RoutingProfileManager] - java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.NullPointerException
java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.NullPointerException
12 Jun 17:59:13 INFO [routing.RoutingProfileManager] - [6] Profiles: 'cycling-electric', location: 'graphs\bike-electric'.
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:192)
        at heigit.ors.routing.RoutingProfileManager.initialize(RoutingProfileManager.java:216)
        at heigit.ors.routing.RoutingProfileManager.getInstance(RoutingProfileManager.java:64)
        at heigit.ors.servlet.listeners.ORSInitContextListener.lambda$contextInitialized$0(ORSInitContextListener.java:43)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.NullPointerException
        at heigit.ors.routing.graphhopper.extensions.core.CoreLMAlgoFactoryDecorator.loadOrDoWork(CoreLMAlgoFactoryDecorator.java:278)
        at heigit.ors.routing.graphhopper.extensions.ORSGraphHopper.loadOrPrepareCoreLM(ORSGraphHopper.java:623)
        at heigit.ors.routing.graphhopper.extensions.ORSGraphHopper.postProcessing(ORSGraphHopper.java:539)
        at com.graphhopper.GraphHopper.process(GraphHopper.java:719)
        at com.graphhopper.GraphHopper.importOrLoad(GraphHopper.java:688)
        at heigit.ors.routing.graphhopper.extensions.ORSGraphHopper.importOrLoad(ORSGraphHopper.java:156)
        at heigit.ors.routing.RoutingProfile.initGraphHopper(RoutingProfile.java:158)
        at heigit.ors.routing.RoutingProfile.<init>(RoutingProfile.java:103)
        at heigit.ors.routing.RoutingProfileLoader.call(RoutingProfileLoader.java:37)
        at heigit.ors.routing.RoutingProfileLoader.call(RoutingProfileLoader.java:21)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        ... 1 more
Caused by: java.util.concurrent.ExecutionException: java.lang.NullPointerException
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:192)
        at heigit.ors.routing.graphhopper.extensions.core.CoreLMAlgoFactoryDecorator.loadOrDoWork(CoreLMAlgoFactoryDecorator.java:274)
        ... 15 more
Caused by: java.lang.NullPointerException
        at heigit.ors.routing.graphhopper.extensions.edgefilters.core.AvoidBordersCoreEdgeFilter.restrictedCountry(AvoidBordersCoreEdgeFilter.java:64)
        at heigit.ors.routing.graphhopper.extensions.edgefilters.core.AvoidBordersCoreEdgeFilter.accept(AvoidBordersCoreEdgeFilter.java:53)
        at heigit.ors.routing.graphhopper.extensions.edgefilters.EdgeFilterSequence.accept(EdgeFilterSequence.java:28)
        at heigit.ors.routing.graphhopper.extensions.edgefilters.EdgeFilterSequence.accept(EdgeFilterSequence.java:28)
        at com.graphhopper.storage.BaseGraph$EdgeIterable.next(BaseGraph.java:979)
        at heigit.ors.routing.graphhopper.extensions.core.TarjansCoreSCCAlgorithm.strongConnect(TarjansCoreSCCAlgorithm.java:152)
        at heigit.ors.routing.graphhopper.extensions.core.TarjansCoreSCCAlgorithm.findComponents(TarjansCoreSCCAlgorithm.java:108)
        at heigit.ors.routing.graphhopper.extensions.core.CoreLandmarkStorage.createLandmarks(CoreLandmarkStorage.java:251)
        at heigit.ors.routing.graphhopper.extensions.core.PrepareCoreLandmarks.doWork(PrepareCoreLandmarks.java:134)
        at heigit.ors.routing.graphhopper.extensions.core.CoreLMAlgoFactoryDecorator$1.run(CoreLMAlgoFactoryDecorator.java:264)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        ... 6 more
12 Jun 17:59:13 INFO [routing.RoutingProfileManager] - [5] FlagEncoders: 1, bits used [UNKNOWN]/64.
12 Jun 17:59:13 INFO [routing.RoutingProfileManager] - [5] Capacity: [UNKNOWN]. (edges - 39319, nodes - 28576)
12 Jun 17:59:13 INFO [routing.RoutingProfileManager] - [5] Total time: 0.054s.
12 Jun 17:59:13 INFO [routing.RoutingProfileManager] - [5] Finished at: 2019-06-12 17:59:13.
12 Jun 17:59:13 INFO [routing.RoutingProfileManager] -
12 Jun 17:59:13 INFO [routing.RoutingProfileManager] - [7] Profiles: 'foot-walking', location: 'graphs\walking'.
12 Jun 17:59:13 INFO [routing.RoutingProfileManager] - [6] FlagEncoders: 1, bits used [UNKNOWN]/64.
12 Jun 17:59:13 INFO [routing.RoutingProfileManager] - [6] Capacity: [UNKNOWN]. (edges - 39664, nodes - 28778)
12 Jun 17:59:13 INFO [routing.RoutingProfileManager] - [6] Total time: 0.069s.
12 Jun 17:59:13 INFO [routing.RoutingProfileManager] - [6] Finished at: 2019-06-12 17:59:13.
12 Jun 17:59:13 INFO [routing.RoutingProfileManager] -
12 Jun 17:59:13 INFO [routing.RoutingProfileManager] - [8] Profiles: 'foot-hiking', location: 'graphs\hiking'.
12 Jun 17:59:13 INFO [routing.RoutingProfileManager] - [7] FlagEncoders: 1, bits used [UNKNOWN]/64.
12 Jun 17:59:13 INFO [routing.RoutingProfileManager] - [7] Capacity: [UNKNOWN]. (edges - 41449, nodes - 30359)
12 Jun 17:59:13 INFO [routing.RoutingProfileManager] - [7] Total time: 0.055s.
12 Jun 17:59:13 INFO [routing.RoutingProfileManager] - [7] Finished at: 2019-06-12 17:59:13.
12 Jun 17:59:13 INFO [routing.RoutingProfileManager] -
12 Jun 17:59:13 INFO [routing.RoutingProfileManager] - [9] Profiles: 'wheelchair', location: 'graphs\wheelchair'.
12 Jun 17:59:13 INFO [routing.RoutingProfileManager] - [8] FlagEncoders: 1, bits used [UNKNOWN]/64.
12 Jun 17:59:13 INFO [routing.RoutingProfileManager] - [8] Capacity: [UNKNOWN]. (edges - 41450, nodes - 30359)
12 Jun 17:59:13 INFO [routing.RoutingProfileManager] - [8] Total time: 0.059s.
12 Jun 17:59:13 INFO [routing.RoutingProfileManager] - [8] Finished at: 2019-06-12 17:59:13.
12 Jun 17:59:13 INFO [routing.RoutingProfileManager] -
12 Jun 17:59:13 INFO [routing.RoutingProfileManager] - [9] FlagEncoders: 1, bits used [UNKNOWN]/64.
12 Jun 17:59:13 INFO [routing.RoutingProfileManager] - [9] Capacity: [UNKNOWN]. (edges - 25175, nodes - 14088)
12 Jun 17:59:13 INFO [routing.RoutingProfileManager] - [9] Total time: 0.06s.
12 Jun 17:59:13 INFO [routing.RoutingProfileManager] - [9] Finished at: 2019-06-12 17:59:13.

```

How to run ORS under debugger?

**Comment by rabidllama** [comment]
If running through intellij, you would debug it the same way as you debug any other program in intellij (using the Debug button to start the run configuration).
It could be a problem with the `app.config` (in `openrouteservice/src/main/resources`) that you are using, so make sure that any file paths in there point to actual files on your system.
Also, make sure that you delete the contents of the folder that stores the generated graphs if you encounter issues as it will always try to load the graphs from the hard drive if they are in that folder

**Comment by ifle** [comment]
@rabidllama When I run using the Debug button I have this error. How to run it with embed Tomcat?
Sorry for very basical questions. I'm from .NET world and my knowledge of java very limited.

```java
org.springframework.beans.factory.BeanDefinitionStoreException: Failed to parse configuration class [heigit.ors.Application]; nested exception is java.lang.IllegalStateException: Failed to introspect annotated methods on class org.springframework.boot.web.servlet.support.SpringBootServletInitializer
	at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:184) ~[spring-context-5.0.8.RELEASE.jar:5.0.8.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:316) ~[spring-context-5.0.8.RELEASE.jar:5.0.8.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:233) ~[spring-context-5.0.8.RELEASE.jar:5.0.8.RELEASE]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:271) ~[spring-context-5.0.8.RELEASE.jar:5.0.8.RELEASE]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:91) ~[spring-context-5.0.8.RELEASE.jar:5.0.8.RELEASE]

SKIPPED

```

I will try to check again the config file. Thanks

**Comment by rabidllama** [comment]
I can't help much with the different IDE setups as I only use the one, but for the original problem - if you go into the app.config and then for the profiles for hgv and car, there is a small bit of text that if you remove it should build ok:
```
"lmsets": "highways,tollways;highways;tollways;country_193;allow_all"
```
needs to be 
```
"lmsets": "highways,tollways;highways;tollways;allow_all"
```
(remove the `country_193;` part).

**Comment by ifle** [comment]
Thanks.

**Comment by rabidllama** [comment]
Closing this now as I believe that the referenced issue fix should correct the problem
