### ISSUE TITLE
Some SRTM elevation tiles are corrupt, e.g. srtm_44_06.tif

### ISSUE THREAD

**Issue by ifle** [GIScience/openrouteservice#548]
Hi,

I tried to load the israel-and-palestine-latest.osm.bz2 file.
During load  I have following error. what am I doing wrong?
```java 

1 INFO [routing.RoutingProfileManager] - ====> Initializing profiles from '/Dev/OSM/israel-and-palestine-latest.osm.bz2' (2 threads) ...
14 Jun 12:49:31 INFO [routing.RoutingProfileManager] -                               
14 Jun 12:49:31 INFO [routing.RoutingProfileManager] -                
14 Jun 12:49:31 INFO [routing.RoutingProfileManager] - [2] Profiles: 'driving-hgv', location: 'graphs\hgv'.
14 Jun 12:49:31 INFO [routing.RoutingProfileManager] - [1] Profiles: 'driving-car', location: 'graphs\car'.
14 Jun 12:50:34 ERROR [routing.RoutingProfileManager] - java.util.concurrent.ExecutionException: java.lang.RuntimeException: Couldn't process file \Dev\OSM\israel-and-palestine-latest.osm.bz2, error: Can't decode srtm_44_06.tif
14 Jun 12:50:34 INFO [routing.RoutingProfileManager] - [3] Profiles: 'cycling-regular', location: 'graphs\bike-regular'.
java.util.concurrent.ExecutionException: java.lang.RuntimeException: Couldn't process file \Dev\OSM\israel-and-palestine-latest.osm.bz2, error: Can't decode srtm_44_06.tif
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at heigit.ors.routing.RoutingProfileManager.initialize(RoutingProfileManager.java:216)
	at heigit.ors.routing.RoutingProfileManager.getInstance(RoutingProfileManager.java:64)
	at heigit.ors.servlet.listeners.ORSInitContextListener.lambda$contextInitialized$0(ORSInitContextListener.java:43)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: Couldn't process file \Dev\OSM\israel-and-palestine-latest.osm.bz2, error: Can't decode srtm_44_06.tif
	at com.graphhopper.reader.osm.OSMReader.writeOsm2Graph(OSMReader.java:406)
	at com.graphhopper.reader.osm.OSMReader.readGraph(OSMReader.java:256)
	at com.graphhopper.GraphHopper.importData(GraphHopper.java:741)
	at com.graphhopper.GraphHopper.process(GraphHopper.java:710)
	at com.graphhopper.GraphHopper.importOrLoad(GraphHopper.java:688)
	at heigit.ors.routing.graphhopper.extensions.ORSGraphHopper.importOrLoad(ORSGraphHopper.java:156)
	at heigit.ors.routing.RoutingProfile.initGraphHopper(RoutingProfile.java:158)
	at heigit.ors.routing.RoutingProfile.<init>(RoutingProfile.java:103)
	at heigit.ors.routing.RoutingProfileLoader.call(RoutingProfileLoader.java:37)
	at heigit.ors.routing.RoutingProfileLoader.call(RoutingProfileLoader.java:21)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)

-- SKIPPED--

a.util.zip.ZipException: invalid block type
	at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:164)
	at java.util.zip.ZipInputStream.read(ZipInputStream.java:194)
	at org.apache.xmlgraphics.image.codec.util.FileCacheSeekableStream.readUntil(FileCacheSeekableStream.java:104)
	at org.apache.xmlgraphics.image.codec.util.FileCacheSeekableStream.read(FileCacheSeekableStream.java:169)
	at org.apache.xmlgraphics.image.codec.util.SeekableStream.readUnsignedShortLE(SeekableStream.java:510)
	at org.apache.xmlgraphics.image.codec.tiff.TIFFDirectory.readUnsignedShort(TIFFDirectory.java:565)
	at org.apache.xmlgraphics.image.codec.tiff.TIFFDirectory.getNumDirectories(TIFFDirectory.java:608)
	at org.apache.xmlgraphics.image.codec.tiff.TIFFImageDecoder.getNumPages(TIFFImageDecoder.java:81)
	at org.apache.xmlgraphics.image.codec.tiff.TIFFImageDecoder.decodeAsRenderedImage(TIFFImageDecoder.java:85)
	at org.apache.xmlgraphics.image.codec.util.ImageDecoderImpl.decodeAsRaster(ImageDecoderImpl.java:136)
	at org.apache.xmlgraphics.image.codec.util.ImageDecoderImpl.decodeAsRaster(ImageDecoderImpl.java:122)
	at com.graphhopper.reader.dem.CGIARProvider.generateRasterFromFile(CGIARProvider.java:113)
```

**Comment by nilsnolde** [comment]
Hi, thanks for the report!

Yes, we heard that recently a few times. Also, in the western US there seem to be some tiles that are corrupt. We did contact the CGIAR team about it, but didn't receive an answer yet (they're downloaded from their WordPress site). We'll keep you updated.

Until then, please specify `gmted` as elevation provider in your `app.config`. It's not as accurate, but better than nothing.

**Comment by ifle** [comment]
Thanks for quick response. I've changed the elevation provider, but have another error. 

```java

14 Jun 13:18:05 INFO [routing.RoutingProfileManager] - [1] Profiles: 'driving-hgv', location: 'graphs\hgv'.
14 Jun 13:18:05 INFO [routing.RoutingProfileManager] - [2] Profiles: 'driving-car', location: 'graphs\car'.
java.util.concurrent.ExecutionException: java.lang.RuntimeException: Couldn't process file \Dev\OSM\israel-and-palestine-latest.osm.bz2, error: Index: 247511798, Size: 0
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at heigit.ors.routing.RoutingProfileManager.initialize(RoutingProfileManager.java:216)
	at heigit.ors.routing.RoutingProfileManager.getInstance(RoutingProfileManager.java:64)
	at heigit.ors.servlet.listeners.ORSInitContextListener.lambda$contextInitialized$0(ORSInitContextListener.java:43)
	at java.lang.Thread.run(Thread.java:748)

-- SKIPPED--

Caused by: java.lang.IndexOutOfBoundsException: Index: 247511798, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
	at java.util.ArrayList.get(ArrayList.java:433)
	at com.graphhopper.storage.MMapDataAccess.getShort(MMapDataAccess.java:282)
	at com.graphhopper.reader.dem.HeightTile.getHeight(HeightTile.java:100)
	at com.graphhopper.reader.dem.AbstractTiffElevationProvider.getEle(AbstractTiffElevationProvider.java:142)
	at com.graphhopper.reader.osm.OSMReader.getElevation(OSMReader.java:782)
	at com.graphhopper.reader.osm.OSMReader.addNode(OSMReader.java:755)
	at com.graphhopper.reader.osm.OSMReader.processNode(OSMReader.java:723)
	at com.graphhopper.reader.osm.OSMReader.writeOsm2Graph(OSMReader.java:373)
	... 15 more
```

default_params from app.config

```json

"default_params": {
            "encoder_flags_size": 8,
            "graphs_root_path": "graphs",
            "elevation_provider": "gmted",
            "elevation_cache_path": "cgiar_provider",
            "elevation_cache_clear": false
            }
```

**Comment by ifle** [comment]
Looks like disabling elevation is workaround

**Comment by rabidllama** [comment]
The SRTM elevation data should now be working again

**Comment by ifle** [comment]
Thanks
