### ISSUE TITLE
Couldn't process file data/osm_file.pbf, error: Can't decode srtm_38_03.tif

### ISSUE THREAD

**Issue by docquantum** [GIScience/openrouteservice#576]
#### Here's what I did

Pulled from docker hub and ran on a linux server using docker compose (giscience/openrouteservice:release_5.0.2).

---
#### Here's what I got

```
ors-back     | 08-Aug-2019 15:08:02.159 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in 8990 ms
ors-back     | 08 Aug 15:08:05 ERROR [routing.RoutingProfileManager] - java.util.concurrent.ExecutionException: java.lang.RuntimeException: Couldn't process file data/osm_file.pbf, error: Can't decode srtm_38_03.tif
ors-back     | java.util.concurrent.ExecutionException: java.lang.RuntimeException: Couldn't process file data/osm_file.pbf, error: Can't decode srtm_38_03.tif
ors-back     |  at java.util.concurrent.FutureTask.report(FutureTask.java:122)
ors-back     |  at java.util.concurrent.FutureTask.get(FutureTask.java:192)
ors-back     |  at heigit.ors.routing.RoutingProfileManager.initialize(RoutingProfileManager.java:218)
ors-back     |  at heigit.ors.routing.RoutingProfileManager.getInstance(RoutingProfileManager.java:66)
ors-back     |  at heigit.ors.servlet.listeners.ORSInitContextListener.lambda$contextInitialized$0(ORSInitContextListener.java:43)
ors-back     |  at java.lang.Thread.run(Thread.java:748)
ors-back     | Caused by: java.lang.RuntimeException: Couldn't process file data/osm_file.pbf, error: Can't decode srtm_38_03.tif
ors-back     |  at com.graphhopper.reader.osm.OSMReader.writeOsm2Graph(OSMReader.java:406)
ors-back     |  at com.graphhopper.reader.osm.OSMReader.readGraph(OSMReader.java:256)
ors-back     |  at com.graphhopper.GraphHopper.importData(GraphHopper.java:741)
ors-back     |  at com.graphhopper.GraphHopper.process(GraphHopper.java:710)
ors-back     |  at com.graphhopper.GraphHopper.importOrLoad(GraphHopper.java:688)
ors-back     |  at heigit.ors.routing.graphhopper.extensions.ORSGraphHopper.importOrLoad(ORSGraphHopper.java:158)
ors-back     |  at heigit.ors.routing.RoutingProfile.initGraphHopper(RoutingProfile.java:185)
ors-back     |  at heigit.ors.routing.RoutingProfile.<init>(RoutingProfile.java:130)
ors-back     |  at heigit.ors.routing.RoutingProfileLoader.call(RoutingProfileLoader.java:37)
ors-back     |  at heigit.ors.routing.RoutingProfileLoader.call(RoutingProfileLoader.java:21)
ors-back     |  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
ors-back     |  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
ors-back     |  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
ors-back     |  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
ors-back     |  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
ors-back     |  ... 1 more
ors-back     | Caused by: java.lang.RuntimeException: Can't decode srtm_38_03.tif
ors-back     |  at com.graphhopper.reader.dem.CGIARProvider.generateRasterFromFile(CGIARProvider.java:115)
ors-back     |  at com.graphhopper.reader.dem.AbstractTiffElevationProvider.getEle(AbstractTiffElevationProvider.java:133)
ors-back     |  at com.graphhopper.reader.dem.MultiSourceElevationProvider.getEle(MultiSourceElevationProvider.java:52)
ors-back     |  at com.graphhopper.reader.osm.OSMReader.getElevation(OSMReader.java:782)
ors-back     |  at com.graphhopper.reader.osm.OSMReader.addNode(OSMReader.java:755)
ors-back     |  at com.graphhopper.reader.osm.OSMReader.processNode(OSMReader.java:723)
ors-back     |  at com.graphhopper.reader.osm.OSMReader.writeOsm2Graph(OSMReader.java:373)
ors-back     |  ... 15 more
ors-back     | Caused by: java.io.EOFException: Unexpected end of ZLIB input stream
ors-back     |  at java.util.zip.InflaterInputStream.fill(InflaterInputStream.java:240)
ors-back     |  at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158)
ors-back     |  at java.util.zip.ZipInputStream.read(ZipInputStream.java:194)
ors-back     |  at org.apache.xmlgraphics.image.codec.util.FileCacheSeekableStream.readUntil(FileCacheSeekableStream.java:104)
ors-back     |  at org.apache.xmlgraphics.image.codec.util.FileCacheSeekableStream.read(FileCacheSeekableStream.java:169)
ors-back     |  at org.apache.xmlgraphics.image.codec.util.SeekableStream.readUnsignedShortLE(SeekableStream.java:510)
ors-back     |  at org.apache.xmlgraphics.image.codec.tiff.TIFFDirectory.readUnsignedShort(TIFFDirectory.java:565)
ors-back     |  at org.apache.xmlgraphics.image.codec.tiff.TIFFDirectory.getNumDirectories(TIFFDirectory.java:608)
ors-back     |  at org.apache.xmlgraphics.image.codec.tiff.TIFFImageDecoder.getNumPages(TIFFImageDecoder.java:81)
ors-back     |  at org.apache.xmlgraphics.image.codec.tiff.TIFFImageDecoder.decodeAsRenderedImage(TIFFImageDecoder.java:85)
ors-back     |  at org.apache.xmlgraphics.image.codec.util.ImageDecoderImpl.decodeAsRaster(ImageDecoderImpl.java:136)
ors-back     |  at org.apache.xmlgraphics.image.codec.util.ImageDecoderImpl.decodeAsRaster(ImageDecoderImpl.java:122)
ors-back     |  at com.graphhopper.reader.dem.CGIARProvider.generateRasterFromFile(CGIARProvider.java:113)
ors-back     |  ... 21 more
ors-back     | 08 Aug 15:08:05 ERROR [routing.RoutingProfileManager] - java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Encoding does not match:
ors-back     | Graphhopper config: pedestrian-ors|speed_factor=1.0|speed_bits=4|turn_costs=false|version=4
ors-back     | Graph: foot|speed_factor=1.0|speed_bits=4|turn_costs=false|version=4, dir:data/graphs/pedestrian-walk/
ors-back     | java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Encoding does not match:
ors-back     | Graphhopper config: pedestrian-ors|speed_factor=1.0|speed_bits=4|turn_costs=false|version=4
ors-back     | Graph: foot|speed_factor=1.0|speed_bits=4|turn_costs=false|version=4, dir:data/graphs/pedestrian-walk/
ors-back     |  at java.util.concurrent.FutureTask.report(FutureTask.java:122)
ors-back     |  at java.util.concurrent.FutureTask.get(FutureTask.java:192)
ors-back     |  at heigit.ors.routing.RoutingProfileManager.initialize(RoutingProfileManager.java:218)
ors-back     |  at heigit.ors.routing.RoutingProfileManager.getInstance(RoutingProfileManager.java:66)
ors-back     |  at heigit.ors.servlet.listeners.ORSInitContextListener.lambda$contextInitialized$0(ORSInitContextListener.java:43)
ors-back     |  at java.lang.Thread.run(Thread.java:748)
ors-back     | Caused by: java.lang.IllegalStateException: Encoding does not match:
ors-back     | Graphhopper config: pedestrian-ors|speed_factor=1.0|speed_bits=4|turn_costs=false|version=4
ors-back     | Graph: foot|speed_factor=1.0|speed_bits=4|turn_costs=false|version=4, dir:data/graphs/pedestrian-walk/
ors-back     |  at com.graphhopper.storage.GraphHopperStorage.loadExisting(GraphHopperStorage.java:297)
ors-back     |  at com.graphhopper.GraphHopper.load(GraphHopper.java:839)
ors-back     |  at heigit.ors.routing.graphhopper.extensions.ORSGraphHopper.load(ORSGraphHopper.java:145)
ors-back     |  at com.graphhopper.GraphHopper.importOrLoad(GraphHopper.java:686)
ors-back     |  at heigit.ors.routing.graphhopper.extensions.ORSGraphHopper.importOrLoad(ORSGraphHopper.java:158)
ors-back     |  at heigit.ors.routing.RoutingProfile.initGraphHopper(RoutingProfile.java:185)
ors-back     |  at heigit.ors.routing.RoutingProfile.<init>(RoutingProfile.java:130)
ors-back     |  at heigit.ors.routing.RoutingProfileLoader.call(RoutingProfileLoader.java:37)
ors-back     |  at heigit.ors.routing.RoutingProfileLoader.call(RoutingProfileLoader.java:21)
ors-back     |  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
ors-back     |  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
ors-back     |  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
ors-back     |  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
ors-back     |  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
ors-back     |  ... 1 more
```

---
#### Here's what I was expecting

For it to work. When accessing the api, I get this at /ors/directions:

```
{
  "error": {
    "code": 2099,
    "message": "Routing service is not ready yet."
  },
  "info": {
    "engine": {
      "version": "5.0.1",
      "build_date": "2019-07-29T07:15:52Z"
    },
    "timestamp": 1565277189369
  }
}
```

When running the container one-shot and using `ls` to see if the data is there, indeed the file osm_file.pbf exists.

---
#### Here's what I think could be improved

Figure out why the server can't decode the data/osm_file.pbf and srtm_38_03.tif files.

**Comment by docquantum** [comment]
Seems that I was running without a tag initially, and after deleting the volumes (and data) associated with the older container, it now runs fine.

**Comment by stevecambridge** [comment]
Hi, what do you mean by running without a tag? I'm seeing this issue now and I'm still not sure how to resolve it.

**Comment by rabidllama** [comment]
Sometimes the srtm data gets corrupt during the download process (this download happens within the GH library), so if there is an error relating to srtm data it is normally best to delete the offending files and start the build again

**Comment by LittleBoxOfChicken** [comment]
Hello, I have the exact same problem in the exact same situation with the same logs (On Ubuntu 18.04). However I did not run without a tag initially. i've tried cleaning all volumes and data but still the problem persists. I'm also not running any other containers.

**Comment by LittleBoxOfChicken** [comment]
I solved the issue. My course of action was:

`$ docker stop [container]`
`$ rm -r elevation_cache/srtm*`
`$ docker-compose up`
