### ISSUE TITLE
Local install throws ApiError: 400 ...  Only a total of 3600 routes are allowed.

### ISSUE THREAD

**Issue by davideps** [GIScience/openrouteservice#718]
Hi Nils,

Thanks to your help, I have ORS up and running locally with just the data our project requires. I can generate routes between two points without difficulty. I'd now like to generate a few large matrices, 70+ coordinate pairs.  When I run this code in Python:

```
client = ors.Client(base_url='http://localhost:8080/ors')
matrix = client.distance_matrix(
    locations=coords,
    profile="driving-car",
    metrics=["duration", "distance"],
    units="km",
    validate=False,
)
```
with a coords list like:
```
[[104.07966, 30.660564], [104.07897, 30.658134], [104.05026, 30.672132], [104.05086, 30.677412], [104.07442, 30.676092], [104.05891, 30.654545], ...]
```
I get this error trace:
```
Traceback (most recent call last):
  File "D:/Projects/AUTOlab/DiDi/python_code/ors_requester.py", line 81, in <module>
    validate=False,
  File "C:\ProgramData\Anaconda3\envs\geo\lib\site-packages\openrouteservice\client.py", line 293, in wrapper
    result = func(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\envs\geo\lib\site-packages\openrouteservice\distance_matrix.py", line 116, in distance_matrix
    return client.request("/v2/matrix/" + profile + '/json', {}, post_json=params, dry_run=dry_run)
  File "C:\ProgramData\Anaconda3\envs\geo\lib\site-packages\openrouteservice\client.py", line 204, in request
    result = self._get_body(response)
  File "C:\ProgramData\Anaconda3\envs\geo\lib\site-packages\openrouteservice\client.py", line 240, in _get_body
    body
openrouteservice.exceptions.ApiError: 400 ({'error': {'code': 6004, 'message': 'Request parameters exceed the server configuration limits. Only a total of 3600 routes are allowed.'}, 'info': {'engine': {'version': '6.0.0', 'build_date': '2020-05-05T05:27:58Z'}, 'timestamp': 1588830477640}})

Process finished with exit code 1
```

I've looked in the docker-compose.yml but do not see any relevant parameter to increase the maximum number of routes. Where should I look?

Thank you (again),
-david

**Comment by nilsnolde** [comment]
Should be merged soon @davideps

**Comment by FinnStutzenstein** [comment]
I was stuck there, too. There is a parameter in the `app.config` (For the docker setup the file is in `docker/conf`) `maximum_routes` which can be set higher (The default is 2500, so for many-to-may 50 points are allowed).

**Comment by Kingshuk-Deb** [comment]
@FinnStutzenstein where can I adjust so as to generate matrix upto 300x300

**Comment by MichaelsJP** [comment]
@Kingshuk-Deb You should be able to set the parameter accordingly. You are welcome to let us know if you succeeded.
