### ISSUE TITLE
Docker run error - missing app.config and fail to install dependencies from org.geotools:gt-main

### ISSUE THREAD

**Issue by leungi** [GIScience/openrouteservice#765]
#### Here's what I did

1. `docker pull openrouteservice/openrouteservice`
2. `docker run -p 4444:8080 --name ors openrouteservice/openrouteservice`
3. open browser to `ohylpy:4444`; this returns OK (note that *ohylpy* is server name)
4. open browser to `ohylpy:4444/ors`; this returns HTTP 404

#### Error capture
![ors-error](https://user-images.githubusercontent.com/30273868/86519347-9148d100-bdff-11ea-94c6-3a75b3e4a1d7.gif)

---
#### Here's what I got
```powershell
ohylpyt{leungi}% sudo docker run -p 4444:8080 --name ors openrouteservice/openrouteservice
### Package openrouteservice and deploy to Tomcat ###
cp: cannot create regular file '/ors-conf/app.config': No such file or directory
10084 [ERROR] Failed to execute goal on project openrouteservice: Could not resolve dependencies for project org.heigit.ors:openrouteservice:war:6.1.1: Failed to collect dependencies at org.geotools:gt-main:jar:19.1: Failed to read artifact descriptor for org.geotools:gt-main:jar:19.1: Could not transfer artifact org.geotools:gt-main:pom:19.1 from/to HeiGIT main (http://repo.heigit.org/artifactory/main): Access denied to: http://repo.heigit.org/artifactory/main/org/geotools/gt-main/19.1/gt-main-19.1.pom -> [Help 1]
10092 [ERROR]
10092 [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
10092 [ERROR] Re-run Maven using the -X switch to enable full debug logging.
10093 [ERROR]
10093 [ERROR] For more information about the errors and possible solutions, please read the following articles:
10093 [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
04-Jul-2020 18:56:03.048 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version:        Apache Tomcat/8.0.32
04-Jul-2020 18:56:03.049 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server built:          Feb 2 2016 19:34:53 UTC
04-Jul-2020 18:56:03.050 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server number:         8.0.32.0
04-Jul-2020 18:56:03.050 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Name:               Linux
04-Jul-2020 18:56:03.050 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Version:            3.10.0-514.6.1.el7.x86_64
04-Jul-2020 18:56:03.050 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Architecture:          amd64
04-Jul-2020 18:56:03.050 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Java Home:             /usr/local/openjdk-8/jre
04-Jul-2020 18:56:03.050 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Version:           1.8.0_252-b09
04-Jul-2020 18:56:03.050 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Vendor:            Oracle Corporation
04-Jul-2020 18:56:03.050 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_BASE:         /usr/local/tomcat
04-Jul-2020 18:56:03.050 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_HOME:         /usr/local/tomcat
04-Jul-2020 18:56:03.051 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.config.file=/usr/local/tomcat/conf/logging.properties
04-Jul-2020 18:56:03.051 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
04-Jul-2020 18:56:03.051 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.awt.headless=true
04-Jul-2020 18:56:03.051 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -XX:TargetSurvivorRatio=75
04-Jul-2020 18:56:03.051 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -XX:SurvivorRatio=64
04-Jul-2020 18:56:03.051 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -XX:MaxTenuringThreshold=3
04-Jul-2020 18:56:03.051 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -XX:+UseConcMarkSweepGC
04-Jul-2020 18:56:03.051 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -XX:+UseParNewGC
04-Jul-2020 18:56:03.051 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -XX:ParallelGCThreads=4
04-Jul-2020 18:56:03.051 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Xms1g
04-Jul-2020 18:56:03.052 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Xmx2g
04-Jul-2020 18:56:03.052 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcom.sun.management.jmxremote
04-Jul-2020 18:56:03.052 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcom.sun.management.jmxremote.port=9001
04-Jul-2020 18:56:03.052 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcom.sun.management.jmxremote.rmi.port=9001
04-Jul-2020 18:56:03.052 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcom.sun.management.jmxremote.authenticate=false
04-Jul-2020 18:56:03.052 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcom.sun.management.jmxremote.ssl=false
04-Jul-2020 18:56:03.052 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.rmi.server.hostname=localhost
04-Jul-2020 18:56:03.052 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.endorsed.dirs=/usr/local/tomcat/endorsed
04-Jul-2020 18:56:03.052 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.base=/usr/local/tomcat
04-Jul-2020 18:56:03.052 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.home=/usr/local/tomcat
04-Jul-2020 18:56:03.053 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.io.tmpdir=/usr/local/tomcat/temp
04-Jul-2020 18:56:03.053 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent The APR based Apache Tomcat Native library which allows optimal performance in production environments was not found on the java.library.path: /usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib
04-Jul-2020 18:56:03.137 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["http-nio-8080"]
04-Jul-2020 18:56:03.148 INFO [main] org.apache.tomcat.util.net.NioSelectorPool.getSharedSelector Using a shared selector for servlet write/read
04-Jul-2020 18:56:03.150 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["ajp-nio-8009"]
04-Jul-2020 18:56:03.151 INFO [main] org.apache.tomcat.util.net.NioSelectorPool.getSharedSelector Using a shared selector for servlet write/read
04-Jul-2020 18:56:03.151 INFO [main] org.apache.catalina.startup.Catalina.load Initialization processed in 347 ms
04-Jul-2020 18:56:03.167 INFO [main] org.apache.catalina.core.StandardService.startInternal Starting service Catalina
04-Jul-2020 18:56:03.168 INFO [main] org.apache.catalina.core.StandardEngine.startInternal Starting Servlet Engine: Apache Tomcat/8.0.32
04-Jul-2020 18:56:03.175 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory /usr/local/tomcat/webapps/ROOT
04-Jul-2020 18:56:03.357 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory /usr/local/tomcat/webapps/ROOT has finished in 182 ms
04-Jul-2020 18:56:03.357 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory /usr/local/tomcat/webapps/docs
04-Jul-2020 18:56:03.374 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory /usr/local/tomcat/webapps/docs has finished in 17 ms
04-Jul-2020 18:56:03.374 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory /usr/local/tomcat/webapps/examples
04-Jul-2020 18:56:03.594 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory /usr/local/tomcat/webapps/examples has finished in 220 ms
04-Jul-2020 18:56:03.594 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory /usr/local/tomcat/webapps/host-manager
04-Jul-2020 18:56:03.611 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory /usr/local/tomcat/webapps/host-manager has finished in 17 ms
04-Jul-2020 18:56:03.611 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory /usr/local/tomcat/webapps/manager
04-Jul-2020 18:56:03.626 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory /usr/local/tomcat/webapps/manager has finished in 14 ms
04-Jul-2020 18:56:03.633 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-nio-8080"]
04-Jul-2020 18:56:03.638 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["ajp-nio-8009"]
04-Jul-2020 18:56:03.639 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in 488 ms
04-Jul-2020 18:56:43.597 INFO [http-nio-8080-exec-1] org.apache.coyote.http11.AbstractHttp11Processor.process Error parsing HTTP request header
 Note: further occurrences of HTTP header parsing errors will be logged at DEBUG level.
 java.lang.IllegalArgumentException: Invalid character (CR or LF) found in method name
        at org.apache.coyote.http11.AbstractNioInputBuffer.parseRequestLine(AbstractNioInputBuffer.java:228)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1009)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:672)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1500)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1456)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)

```

---
#### Here's what I was expecting
Since I'm not building from docker image from source, I expect `docker run` to not return the *ERROR* messages shown in above shell output, as all the required files should be embedded in built image.

I believe these error are the reason why endpoint `ohylpy:4444/ors` doesn't work.

---
#### Here's what I think could be improved
Looking for the community/guru insights 😄

**Comment by rabidllama** [comment]
It seems that the last update to the docker configuration to fix problems people were having with app.configs not being updated after reloading has broken the setup from docker hub... We will get around to fixing as soon as we can, but for now you can either try using an older tag from docker hub, or cloning the repo and then running docker from there

**Comment by rabidllama** [comment]
Getting openrouteservice to run through docker hub is quite difficult as there are configurations that are needed during the container building which are specific to the individual setup, and from my understanding, when you pull from the docker hub, all of these are prebuilt and so these configurations can't be set.

We are looking into ways of trying to get openrouteservice to work "out of the box" from dockerhub, but as this will likely be a fairly complex task I can't say for sure when it will be sorted.

For now though, the best option is to clone the openrouteservice repo and then run it from there. There are some instructions in the docker folder of the repo which should help to get things up and running.

**Comment by nilsnolde** [comment]
I can't say much about the `Failed to execute goal on project openrouteservice`. If there's anything missing in the docker image related to authorization of artifacts it shouldn't be a problem to add them from the source repository.

For the `app.config` bug: d'oh.. there's a `mkdir /ors-conf` missing in the Dockerfile, has nothing to do with Dockerhub, as it'll also fail on a repo setup. Can you try this patch @leungi :
```
diff --git a/Dockerfile b/Dockerfile
index 18af4ef4..412e0346 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -16,7 +16,7 @@ COPY $APP_CONFIG /ors-core/openrouteservice/src/main/resources/app.config.sample
 RUN wget -q https://archive.apache.org/dist/tomcat/tomcat-8/v8.0.32/bin/apache-tomcat-8.0.32.tar.gz -O /tmp/tomcat.tar.gz && \
     cd /tmp && \
     tar xvfz tomcat.tar.gz && \
-    mkdir /usr/local/tomcat && \
+    mkdir /usr/local/tomcat /ors-conf && \
     cp -R /tmp/apache-tomcat-8.0.32/* /usr/local/tomcat/ && \
     # Install dependencies and locales
     apt-get update -qq && apt-get install -qq -y locales nano maven moreutils jq && \
```

**Comment by leungi** [comment]
@rabidllama , @nilsnolde : thanks for prompt response 🙇‍♂️

I'll try your suggestion and update y'all.

**Comment by leungi** [comment]
Update.

Image built from source seems to be successful with the below `Dockerfile` and `docker-compose.yml`.

However, the created container `ors-app` exits on start, and `docker start` doesn't help.

I was also expecting the respective folders in host (e.g., `./graphs`,  `./elevation_cache`) to be populated with files after built, but not the case.

Note:

- the `.pbf` obtained from GeoFabrik is saved in root path as `us-south-latest.osm.pbf`
- the volume mapping `./us-south-latest.osm.pbf:/ors-core/data/osm_file.pbf` commented out, as uncommenting leads to error about path not found.

    - initially thought it may be due to the folder and filename having the same name, but changing to `./us-south-latest-osm.pbf` doesn't solve issue either.
    - since *.osm.pbf is copied to image during build, not mounting this volume shouldn't be the reason for container start-up fail

- `BUILD_GRAPHS` set to `True` since a new *.osm.pbf is used.

Look forward to your guidance 🙏

#### Dockerfile
```
FROM openjdk:8-jdk

ENV MAVEN_OPTS="-Dmaven.repo.local=.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
ENV MAVEN_CLI_OPTS="--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"

ARG APP_CONFIG=./openrouteservice/src/main/resources/app.config.sample
ARG OSM_FILE=./us-south-latest.osm.pbf

WORKDIR /ors-core

COPY openrouteservice /ors-core/openrouteservice
COPY $OSM_FILE /ors-core/data/osm_file.pbf
COPY $APP_CONFIG /ors-core/openrouteservice/src/main/resources/app.config.sample

# Install tomcat
RUN wget --no-check-certificate -q https://archive.apache.org/dist/tomcat/tomcat-8/v8.0.32/bin/apache-tomcat-8.0.32.tar.gz -O /tmp/tomcat.tar.gz && \
    cd /tmp && \
    tar xvfz tomcat.tar.gz && \
#    mkdir /usr/local/tomcat && \
    mkdir /usr/local/tomcat /ors-conf && \
    cp -R /tmp/apache-tomcat-8.0.32/* /usr/local/tomcat/ && \
    # Install dependencies and locales
    apt-get update -qq && apt-get install -qq -y locales nano maven moreutils jq && \
    locale-gen en_US.UTF-8 && \
    # Rename to app.config
    cp /ors-core/openrouteservice/src/main/resources/app.config.sample /ors-core/openrouteservice/src/main/resources/app.config && \
    # Replace paths in app.config to match docker setup
    jq '.ors.services.routing.sources[0] = "data/osm_file.pbf"' /ors-core/openrouteservice/src/main/resources/app.config |sponge /ors-core/openrouteservice/src/main/resources/app.config && \
    jq '.ors.services.routing.profiles.default_params.elevation_cache_path = "data/elevation_cache"' /ors-core/openrouteservice/src/main/resources/app.config |sponge /ors-core/openrouteservice/src/main/resources/app.config && \
    jq '.ors.services.routing.profiles.default_params.graphs_root_path = "data/graphs"' /ors-core/openrouteservice/src/main/resources/app.config |sponge /ors-core/openrouteservice/src/main/resources/app.config && \
    # init_threads = 1, > 1 been reported some issues
    jq '.ors.services.routing.init_threads = 1' /ors-core/openrouteservice/src/main/resources/app.config |sponge /ors-core/openrouteservice/src/main/resources/app.config && \
    # Delete all profiles but car
    jq 'del(.ors.services.routing.profiles.active[1,2,3,4,5,6,7,8])' /ors-core/openrouteservice/src/main/resources/app.config |sponge /ors-core/openrouteservice/src/main/resources/app.config

COPY ./docker-entrypoint.sh /docker-entrypoint.sh

# Start the container
EXPOSE 8080
ENTRYPOINT ["/bin/bash", "/docker-entrypoint.sh"]
```

#### docker-compose.yml
```
version: '2.4'
services:
  ors-app:
    container_name: ors-app
    ports:
      - 8080:8080
    image: openrouteservice/openrouteservice:latest
    build:
      context: ../
      args:
        APP_CONFIG: ./openrouteservice/src/main/resources/app.config.sample
        OSM_FILE: ./us-south-latest.osm.pbf
    volumes:
      - ./graphs:/ors-core/data/graphs
      - ./elevation_cache:/ors-core/data/elevation_cache
      - ./logs/ors:/var/log/ors
      - ./logs/tomcat:/usr/local/tomcat/logs
      - ./conf:/ors-conf
      #- ./us-south-latest.osm.pbf:/ors-core/data/osm_file.pbf
    environment:
      - BUILD_GRAPHS=True  # Forces the container to rebuild the graphs, e.g. when PBF is changed
      - "JAVA_OPTS=-Djava.awt.headless=true -server -XX:TargetSurvivorRatio=75 -XX:SurvivorRatio=64 -XX:MaxTenuringThreshold=3 -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:ParallelGCThreads=4 -Xms1g -Xmx2g"
      - "CATALINA_OPTS=-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=9001 -Dcom.sun.management.jmxremote.rmi.port=9001 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=localhost"
```

**Comment by rabidllama** [comment]
If you run `docker logs --tail 200 ors-app` it should show you if there was an error within Tomcat. Looking at what you said though, I would assume the problem is because you need to tell java to use more memory. In the `JAVA_OPTS` of the docker-compose, that is done with the `-Xms1g` and `-Xmx2g` properties. Generally you need to give it at least twice the size of the pbf file, so if the pbf is 3GB, then these should be changed to `-Xms6g -Xmx6g`. Obviously you need to have that much free RAM in the host machine.

If you do a `docker inspect ors-app` then I believe it should show you why the container terminated (under `state`) but I am not sure if it would show the error there as it would be tomcat that terminates and not docker itself...

**Comment by nilsnolde** [comment]
A build does not start anything. Only when a container is started it will start to process your OSM file. As for the OSM file path issue, that's not working because you changed the location of the PBF file `./us-south-latest.osm.pbf` is referring to the path of `Dockerfile` for the build and the path of `docker-compose.yml` on container startup.

**Comment by leungi** [comment]
Good call @rabidllama.

Thanks for tip @nilsnolde; I see the error is due to the host volume specified having the same name as the OSM .pbf file 😅

So it seems `docker-entrypoint.sh` is the reason - Windows EOL *\r*. Reformatted to UNIX format, and facing the same original with maven.


#### Container log
```
(base) PS D:\openrouteservice\docker> docker logs --tail 200 ors-app
/docker-entrypoint.sh: line 2: $'\r': command not found
/docker-entrypoint.sh: line 6: $'\r': command not found
/docker-entrypoint.sh: line 36: syntax error: unexpected end of file
/docker-entrypoint.sh: line 2: $'\r': command not found
/docker-entrypoint.sh: line 6: $'\r': command not found
/docker-entrypoint.sh: line 36: syntax error: unexpected end of file
(base) PS D:\openrouteservice\docker> docker inspect ors-app
[
    {
        "Id": "d3cbfb90ac7a389ca743124d300ea19e5c90f71387bb3da308698c48978b8060",
        "Created": "2020-07-14T05:59:34.484631809Z",
        "Path": "/bin/bash",
        "Args": [
            "/docker-entrypoint.sh"
        ],
        "State": {
            "Status": "exited",
            "Running": false,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 0,
            "ExitCode": 2,
            "Error": "",
            "StartedAt": "2020-07-14T05:59:44.543319212Z",
            "FinishedAt": "2020-07-14T05:59:44.553516178Z"
        },
       ...
```

#### Rebuild using fixed docker-entrypoint.sh
```bash
 ---> Using cache
 ---> a06b75c59fcc
Step 11/13 : COPY ./docker-entrypoint.sh /docker-entrypoint.sh
 ---> 037b0971451a
Step 12/13 : EXPOSE 8080
 ---> Running in 881505b7a35e
Removing intermediate container 881505b7a35e
 ---> 71b45e3fbef7
Step 13/13 : ENTRYPOINT ["/bin/bash", "/docker-entrypoint.sh"]
 ---> Running in fced0e3306a7
Removing intermediate container fced0e3306a7
 ---> 59c48ffe1500

Successfully built 59c48ffe1500
Successfully tagged openrouteservice/openrouteservice:latest
Recreating ors-app ... done
Attaching to ors-app
ors-app    | ### Package openrouteservice and deploy to Tomcat ###
ors-app    | 9779 [ERROR] Plugin org.springframework.boot:spring-boot-maven-plugin:2.0.4.RELEASE or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.springframework.boot:spring-boot-maven-plugin:jar:2.0.4.RELEASE: Could not transfer artifact org.springframework.boot:spring-boot-maven-plugin:pom:2.0.4.RELEASE from/to central (https://repo.maven.apache.org/maven2): sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target -> [Help 1]
ors-app    | 9794 [ERROR]
ors-app    | 9794 [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
ors-app    | 9795 [ERROR] Re-run Maven using the -X switch to enable full debug logging.
ors-app    | 9796 [ERROR]
ors-app    | 9796 [ERROR] For more information about the errors and possible solutions, please read the following articles:
ors-app    | 9798 [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginResolutionException
ors-app    | 14-Jul-2020 06:09:10.869 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version:        Apache Tomcat/8.0.32
ors-app    | 14-Jul-2020 06:09:10.871 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server built:          Feb 2 2016 19:34:53 UTC
ors-app    | 14-Jul-2020 06:09:10.871 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server number:         8.0.32.0
ors-app    | 14-Jul-2020 06:09:10.871 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Name:               Linux
```

**Comment by leungi** [comment]
Glad to have solved this problem 🤩

Had to add these args for `MAVEN_OPTS` in the Dockerfile:

`-Dmaven.wagon.http.ssl.insecure=true -Dmaven.wagon.http.ssl.allowall=true -Dmaven.wagon.http.ssl.ignore.validity.dates=true`

Thank you @rabidllama and @nilsnolde once again for the guidance along the way 🙏
