### ISSUE TITLE
Unable to compute a distance/duration matrix with cycling-regular profile

### ISSUE THREAD

**Issue by jfalameda** [GIScience/openrouteservice#810]
Hi,

I am trying to compute a distance/duration matrix for a cycling-regular profile. The driving-car profile wors with no issues, but once I change to another of the loaded profiles, it fails with the following error: 
`Unable to compute a distance/duration matrix.`

Looking at the logs, I found the following exception:

```
16 Sep 19:40:59 ERROR [routing.RoutingProfile] - java.lang.Exception: Search exceeds the limit of visited nodes.
ors      | 16 Sep 19:40:59 ERROR [errors.CommonResponseEntityExceptionHandler] - Exception
ors      | org.heigit.ors.exceptions.InternalServerException: Unable to compute a distance/duration matrix.
ors      | 	at org.heigit.ors.routing.RoutingProfile.computeMatrix(RoutingProfile.java:652) ~[classes/:6.3.0]
ors      | 	at org.heigit.ors.routing.RoutingProfileManager.computeMatrix(RoutingProfileManager.java:620) ~[classes/:6.3.0]
ors      | 	at org.heigit.ors.api.requests.matrix.MatrixRequestHandler.generateMatrixFromRequest(MatrixRequestHandler.java:45) ~[classes/:6.3.0]
ors      | 	at org.heigit.ors.api.controllers.MatrixAPI.getJsonMime(MatrixAPI.java:98) ~[classes/:6.3.0]
ors      | 	at org.heigit.ors.api.controllers.MatrixAPI.getDefault(MatrixAPI.java:84) ~[classes/:6.3.0]
ors      | 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
ors      | 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
ors      | 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
ors      | 	at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
```

Steps to reproduce:

Docker based ORS (latest version).
Using the following PBF file https://download.geofabrik.de/europe/sweden-latest.osm.pbf
Using the following configuration file
https://gist.github.com/jfalameda/45cc810b00273be151602960f9de204e
Doing the following request
`POST http://localhost:8080/ors/v2/matrix/cycling-regular`
Request body https://gist.github.com/jfalameda/14da5231c0faa18cc494902677c92242

**Update:**
I tried removing elements from the matrix until I left 3, then it worked. For some reason the `MatrixServiceSettings. getMaximumVisitedNodes()` is very low for cycling-regular, which I cannot see any reference for in the settings.

Thanks.

**Comment by MichaelsJP** [comment]
This issue can be solved by setting the `maximum_visited_nodes` parameter higher than the default value.

https://github.com/GIScience/openrouteservice/blob/b69983ee3fd93f484bc697036001fb6ff0bb4b6e/ors-config.yml#L86
