### ISSUE TITLE
Can't decode srtm_38_03.tif

### ISSUE THREAD

**Issue by mshvarts** [GIScience/openrouteservice#845]
#### Here's what I did

trying to run "docker-compose up" in the docker folder after pulling from github repository
using docker-compose 1.27.4 that I installed using pip3
tried running on ubuntu 18 and WSL2. 

---
#### Here's what I got

`ors-app    | 27 Dec 21:24:07 ERROR [routing.RoutingProfileManager] - java.util.concurrent.ExecutionException: java.lang.RuntimeException: Couldn't process file data/osm_file.pbf, error: Can't decode srtm_38_03.tif
ors-app    | 27 Dec 21:24:07 ERROR [routing.RoutingProfileManager] - Failed to initialize RoutingProfileManager instance.
ors-app    | java.util.concurrent.ExecutionException: java.lang.RuntimeException: Couldn't process file data/osm_file.pbf, error: Can't decode srtm_38_03.tif`

Full log:
```jelly@jelly-VirtualBox:~/Desktop/openrouteservice/docker$ docker-compose up
Creating network "docker_default" with the default driver
Pulling ors-app (openrouteservice/openrouteservice:latest)...
latest: Pulling from openrouteservice/openrouteservice
6c33745f49b4: Pull complete
c87cd3c61e27: Pull complete
05a3c799ec37: Pull complete
a61c38f966ac: Pull complete
396b39798a69: Pull complete
576b6480761a: Pull complete
0d66e5d46fdf: Pull complete
1aa2971c52c4: Pull complete
e07f6a3652b1: Pull complete
7b6216f13c62: Pull complete
0cc59a78c17c: Pull complete
0fc730f36e07: Pull complete
94c96ce8ea63: Pull complete
Digest: sha256:54fb2e0e01f917425a9b2e6aa008d2ed8d2bedd76ffb39763c6b21245c6e5efc
Status: Downloaded newer image for openrouteservice/openrouteservice:latest
Creating ors-app ... done
Attaching to ors-app
ors-app    | ### Package openrouteservice and deploy to Tomcat ###
ors-app    | WARNING: An illegal reflective access operation has occurred
ors-app    | WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/usr/share/maven/lib/guice.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
ors-app    | WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
ors-app    | WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
ors-app    | WARNING: All illegal access operations will be denied in a future release
ors-app    | NOTE: Picked up JDK_JAVA_OPTIONS:  --add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNNAMED --add-opens=java.rmi/sun.rmi.transport=ALL-UNNAMED
ors-app    | 27-Dec-2020 21:23:34.720 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version:        Apache Tomcat/8.5.39
ors-app    | 27-Dec-2020 21:23:34.740 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server built:          Mar 14 2019 11:24:26 UTC
ors-app    | 27-Dec-2020 21:23:34.741 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server number:         8.5.39.0
ors-app    | 27-Dec-2020 21:23:34.743 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Name:               Linux
ors-app    | 27-Dec-2020 21:23:34.744 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Version:            4.15.0-128-generic
ors-app    | 27-Dec-2020 21:23:34.744 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Architecture:          amd64
ors-app    | 27-Dec-2020 21:23:34.745 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Java Home:             /usr/local/openjdk-11
ors-app    | 27-Dec-2020 21:23:34.746 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Version:           11.0.9.1+1
ors-app    | 27-Dec-2020 21:23:34.747 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Vendor:            Oracle Corporation
ors-app    | 27-Dec-2020 21:23:34.749 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_BASE:         /usr/local/tomcat
ors-app    | 27-Dec-2020 21:23:34.750 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_HOME:         /usr/local/tomcat
ors-app    | 27-Dec-2020 21:23:34.753 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.base/java.lang=ALL-UNNAMED
ors-app    | 27-Dec-2020 21:23:34.754 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.base/java.io=ALL-UNNAMED
ors-app    | 27-Dec-2020 21:23:34.756 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: --add-opens=java.rmi/sun.rmi.transport=ALL-UNNAMED
ors-app    | 27-Dec-2020 21:23:34.756 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.config.file=/usr/local/tomcat/conf/logging.properties
ors-app    | 27-Dec-2020 21:23:34.757 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
ors-app    | 27-Dec-2020 21:23:34.758 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.awt.headless=true
ors-app    | 27-Dec-2020 21:23:34.759 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -XX:TargetSurvivorRatio=75
ors-app    | 27-Dec-2020 21:23:34.760 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -XX:SurvivorRatio=64
ors-app    | 27-Dec-2020 21:23:34.761 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -XX:MaxTenuringThreshold=3
ors-app    | 27-Dec-2020 21:23:34.762 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -XX:+UseG1GC
ors-app    | 27-Dec-2020 21:23:34.762 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -XX:+ScavengeBeforeFullGC
ors-app    | 27-Dec-2020 21:23:34.763 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -XX:ParallelGCThreads=4
ors-app    | 27-Dec-2020 21:23:34.764 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Xms1g
ors-app    | 27-Dec-2020 21:23:34.764 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Xmx2g
ors-app    | 27-Dec-2020 21:23:34.765 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djdk.tls.ephemeralDHKeySize=2048
ors-app    | 27-Dec-2020 21:23:34.766 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.protocol.handler.pkgs=org.apache.catalina.webresources
ors-app    | 27-Dec-2020 21:23:34.771 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dorg.apache.catalina.security.SecurityListener.UMASK=0027
ors-app    | 27-Dec-2020 21:23:34.776 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcom.sun.management.jmxremote
ors-app    | 27-Dec-2020 21:23:34.777 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcom.sun.management.jmxremote.port=9001
ors-app    | 27-Dec-2020 21:23:34.778 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcom.sun.management.jmxremote.rmi.port=9001
ors-app    | 27-Dec-2020 21:23:34.779 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcom.sun.management.jmxremote.authenticate=false
ors-app    | 27-Dec-2020 21:23:34.780 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcom.sun.management.jmxremote.ssl=false
ors-app    | 27-Dec-2020 21:23:34.781 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.rmi.server.hostname=localhost
ors-app    | 27-Dec-2020 21:23:34.781 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dignore.endorsed.dirs=
ors-app    | 27-Dec-2020 21:23:34.782 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.base=/usr/local/tomcat
ors-app    | 27-Dec-2020 21:23:34.783 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.home=/usr/local/tomcat
ors-app    | 27-Dec-2020 21:23:34.784 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.io.tmpdir=/usr/local/tomcat/temp
ors-app    | 27-Dec-2020 21:23:34.784 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent The APR based Apache Tomcat Native library which allows optimal performance in production environments was not found on the java.library.path: [/usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib]
ors-app    | 27-Dec-2020 21:23:34.864 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["http-nio-8080"]
ors-app    | 27-Dec-2020 21:23:34.891 INFO [main] org.apache.tomcat.util.net.NioSelectorPool.getSharedSelector Using a shared selector for servlet write/read
ors-app    | 27-Dec-2020 21:23:34.925 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["ajp-nio-8009"]
ors-app    | 27-Dec-2020 21:23:34.941 INFO [main] org.apache.tomcat.util.net.NioSelectorPool.getSharedSelector Using a shared selector for servlet write/read
ors-app    | 27-Dec-2020 21:23:34.944 INFO [main] org.apache.catalina.startup.Catalina.load Initialization processed in 841 ms
ors-app    | 27-Dec-2020 21:23:35.068 INFO [main] org.apache.catalina.core.StandardService.startInternal Starting service [Catalina]
ors-app    | 27-Dec-2020 21:23:35.071 INFO [main] org.apache.catalina.core.StandardEngine.startInternal Starting Servlet Engine: Apache Tomcat/8.5.39
ors-app    | 27-Dec-2020 21:23:35.126 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Deploying web application archive [/usr/local/tomcat/webapps/ors.war]
ors-app    | 
ors-app    |   .   ____          _            __ _ _
ors-app    |  /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
ors-app    | ( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
ors-app    |  \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
ors-app    |   '  |____| .__|_| |_|_| |_\__, | / / / /
ors-app    |  =========|_|==============|___/=/_/_/_/
ors-app    |  :: Spring Boot ::        (v2.3.5.RELEASE)
ors-app    | 
ors-app    | 27 Dec 21:23:47 INFO [ors.Application] - Starting Application v6.3.2 on 78b527818443 with PID 80 (/usr/local/tomcat/webapps/ors/WEB-INF/classes started by root in /ors-core)
ors-app    | 27 Dec 21:23:47 DEBUG [ors.Application] - Running with Spring Boot v2.3.5.RELEASE, Spring v5.2.10.RELEASE
ors-app    | 27 Dec 21:23:47 INFO [ors.Application] - No active profile set, falling back to default profiles: default
ors-app    | SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
ors-app    | SLF4J: Defaulting to no-operation (NOP) logger implementation
ors-app    | SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
ors-app    | 27 Dec 21:23:52 INFO [ors.Application] - Started Application in 7.252 seconds (JVM running for 19.364)
ors-app    | 27-Dec-2020 21:23:52.768 INFO [localhost-startStop-1] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
ors-app    | <?xml version="1.0" ?>
ors-app    | <Configuration>
ors-app    |   <Properties>
ors-app    |     <Property name="filename">/var/log/ors/ors-logs.log</Property>
ors-app    |   </Properties>
ors-app    | </Configuration>
ors-app    | 27 Dec 21:23:52 INFO [routing.RoutingProfileManager] -  Total - 1024 MB, Free - 602.46 MB, Max: 2 GB, Used - 421.54 MB
ors-app    | 27 Dec 21:23:52 INFO [routing.RoutingProfileManager] -       
ors-app    | 27-Dec-2020 21:23:52.946 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Deployment of web application archive [/usr/local/tomcat/webapps/ors.war] has finished in [17,819] ms
ors-app    | 27-Dec-2020 21:23:52.952 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory [/usr/local/tomcat/webapps/ROOT]
ors-app    | 27 Dec 21:23:53 INFO [routing.RoutingProfileManager] - ====> Initializing profiles from 'data/osm_file.pbf' (1 threads) ...
ors-app    | 27 Dec 21:23:53 INFO [routing.RoutingProfileManager] -                               
ors-app    | 27 Dec 21:23:53 INFO [routing.RoutingProfileManager] -                
ors-app    | 27-Dec-2020 21:23:53.056 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [/usr/local/tomcat/webapps/ROOT] has finished in [104] ms
ors-app    | 27-Dec-2020 21:23:53.070 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory [/usr/local/tomcat/webapps/docs]
ors-app    | 27-Dec-2020 21:23:53.136 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [/usr/local/tomcat/webapps/docs] has finished in [66] ms
ors-app    | 27-Dec-2020 21:23:53.140 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory [/usr/local/tomcat/webapps/manager]
ors-app    | 27 Dec 21:23:53 INFO [routing.RoutingProfile] - [1] Profiles: 'driving-car', location: 'data/graphs/car'.
ors-app    | 27-Dec-2020 21:23:53.261 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [/usr/local/tomcat/webapps/manager] has finished in [121] ms
ors-app    | 27-Dec-2020 21:23:53.264 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory [/usr/local/tomcat/webapps/examples]
ors-app    | 27-Dec-2020 21:23:53.763 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [/usr/local/tomcat/webapps/examples] has finished in [491] ms
ors-app    | 27-Dec-2020 21:23:53.765 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory [/usr/local/tomcat/webapps/host-manager]
ors-app    | 27-Dec-2020 21:23:53.840 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory [/usr/local/tomcat/webapps/host-manager] has finished in [75] ms
ors-app    | 27-Dec-2020 21:23:53.849 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-nio-8080"]
ors-app    | 27-Dec-2020 21:23:53.941 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["ajp-nio-8009"]
ors-app    | 27-Dec-2020 21:23:54.001 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in 19056 ms
ors-app    | 27 Dec 21:24:07 ERROR [routing.RoutingProfileManager] - java.util.concurrent.ExecutionException: java.lang.RuntimeException: Couldn't process file data/osm_file.pbf, error: Can't decode srtm_38_03.tif
ors-app    | 27 Dec 21:24:07 ERROR [routing.RoutingProfileManager] - Failed to initialize RoutingProfileManager instance.
ors-app    | java.util.concurrent.ExecutionException: java.lang.RuntimeException: Couldn't process file data/osm_file.pbf, error: Can't decode srtm_38_03.tif
ors-app    | 	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:?]
ors-app    | 	at java.util.concurrent.FutureTask.get(FutureTask.java:191) ~[?:?]
ors-app    | 	at org.heigit.ors.routing.RoutingProfileManager.initialize(RoutingProfileManager.java:164) ~[classes/:6.3.2]
ors-app    | 	at org.heigit.ors.routing.RoutingProfileManager.getInstance(RoutingProfileManager.java:59) ~[classes/:6.3.2]
ors-app    | 	at org.heigit.ors.servlet.listeners.ORSInitContextListener.lambda$contextInitialized$0(ORSInitContextListener.java:40) ~[classes/:6.3.2]
ors-app    | 	at java.lang.Thread.run(Thread.java:834) [?:?]
ors-app    | Caused by: java.lang.RuntimeException: Couldn't process file data/osm_file.pbf, error: Can't decode srtm_38_03.tif
ors-app    | 	at com.graphhopper.reader.osm.OSMReader.writeOsm2Graph(OSMReader.java:326) ~[graphhopper-reader-osm-v0.13.9.jar:?]
ors-app    | 	at com.graphhopper.reader.osm.OSMReader.readGraph(OSMReader.java:178) ~[graphhopper-reader-osm-v0.13.9.jar:?]
ors-app    | 	at com.graphhopper.GraphHopper.importData(GraphHopper.java:735) ~[graphhopper-core-v0.13.9.jar:?]
ors-app    | 	at com.graphhopper.GraphHopper.readData(GraphHopper.java:714) ~[graphhopper-core-v0.13.9.jar:?]
ors-app    | 	at com.graphhopper.GraphHopper.process(GraphHopper.java:701) ~[graphhopper-core-v0.13.9.jar:?]
ors-app    | 	at com.graphhopper.GraphHopper.importOrLoad(GraphHopper.java:680) ~[graphhopper-core-v0.13.9.jar:?]
ors-app    | 	at org.heigit.ors.routing.graphhopper.extensions.ORSGraphHopper.importOrLoad(ORSGraphHopper.java:159) ~[classes/:6.3.2]
ors-app    | 	at org.heigit.ors.routing.RoutingProfile.initGraphHopper(RoutingProfile.java:191) ~[classes/:6.3.2]
ors-app    | 	at org.heigit.ors.routing.RoutingProfile.<init>(RoutingProfile.java:135) ~[classes/:6.3.2]
ors-app    | 	at org.heigit.ors.routing.RoutingProfileLoader.call(RoutingProfileLoader.java:35) ~[classes/:6.3.2]
ors-app    | 	at org.heigit.ors.routing.RoutingProfileLoader.call(RoutingProfileLoader.java:21) ~[classes/:6.3.2]
ors-app    | 	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
ors-app    | 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
ors-app    | 	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
ors-app    | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
ors-app    | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
ors-app    | 	... 1 more
ors-app    | Caused by: java.lang.RuntimeException: Can't decode srtm_38_03.tif
ors-app    | 	at com.graphhopper.reader.dem.CGIARProvider.generateRasterFromFile(CGIARProvider.java:112) ~[graphhopper-core-v0.13.9.jar:?]
ors-app    | 	at com.graphhopper.reader.dem.AbstractTiffElevationProvider.getEle(AbstractTiffElevationProvider.java:133) ~[graphhopper-core-v0.13.9.jar:?]
ors-app    | 	at com.graphhopper.reader.dem.MultiSourceElevationProvider.getEle(MultiSourceElevationProvider.java:52) ~[graphhopper-core-v0.13.9.jar:?]
ors-app    | 	at com.graphhopper.reader.osm.OSMReader.getElevation(OSMReader.java:715) ~[graphhopper-reader-osm-v0.13.9.jar:?]
ors-app    | 	at org.heigit.ors.routing.graphhopper.extensions.ORSOSMReader.getElevation(ORSOSMReader.java:433) ~[classes/:6.3.2]
ors-app    | 	at com.graphhopper.reader.osm.OSMReader.addNode(OSMReader.java:676) ~[graphhopper-reader-osm-v0.13.9.jar:?]
ors-app    | 	at com.graphhopper.reader.osm.OSMReader.processNode(OSMReader.java:641) ~[graphhopper-reader-osm-v0.13.9.jar:?]
ors-app    | 	at com.graphhopper.reader.osm.OSMReader.writeOsm2Graph(OSMReader.java:293) ~[graphhopper-reader-osm-v0.13.9.jar:?]
ors-app    | 	at com.graphhopper.reader.osm.OSMReader.readGraph(OSMReader.java:178) ~[graphhopper-reader-osm-v0.13.9.jar:?]
ors-app    | 	at com.graphhopper.GraphHopper.importData(GraphHopper.java:735) ~[graphhopper-core-v0.13.9.jar:?]
ors-app    | 	at com.graphhopper.GraphHopper.readData(GraphHopper.java:714) ~[graphhopper-core-v0.13.9.jar:?]
ors-app    | 	at com.graphhopper.GraphHopper.process(GraphHopper.java:701) ~[graphhopper-core-v0.13.9.jar:?]
ors-app    | 	at com.graphhopper.GraphHopper.importOrLoad(GraphHopper.java:680) ~[graphhopper-core-v0.13.9.jar:?]
ors-app    | 	at org.heigit.ors.routing.graphhopper.extensions.ORSGraphHopper.importOrLoad(ORSGraphHopper.java:159) ~[classes/:6.3.2]
ors-app    | 	at org.heigit.ors.routing.RoutingProfile.initGraphHopper(RoutingProfile.java:191) ~[classes/:6.3.2]
ors-app    | 	at org.heigit.ors.routing.RoutingProfile.<init>(RoutingProfile.java:135) ~[classes/:6.3.2]
ors-app    | 	at org.heigit.ors.routing.RoutingProfileLoader.call(RoutingProfileLoader.java:35) ~[classes/:6.3.2]
ors-app    | 	at org.heigit.ors.routing.RoutingProfileLoader.call(RoutingProfileLoader.java:21) ~[classes/:6.3.2]
ors-app    | 	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
ors-app    | 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
ors-app    | 	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
ors-app    | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
ors-app    | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
ors-app    | 	... 1 more
ors-app    | Caused by: java.io.EOFException
ors-app    | 	at org.apache.xmlgraphics.image.codec.util.SeekableStream.readUnsignedShort(SeekableStream.java:483) ~[xmlgraphics-commons-2.3.jar:2.3]
ors-app    | 	at org.apache.xmlgraphics.image.codec.tiff.TIFFDirectory.getNumDirectories(TIFFDirectory.java:590) ~[xmlgraphics-commons-2.3.jar:2.3]
ors-app    | 	at org.apache.xmlgraphics.image.codec.tiff.TIFFImageDecoder.getNumPages(TIFFImageDecoder.java:81) ~[xmlgraphics-commons-2.3.jar:2.3]
ors-app    | 	at org.apache.xmlgraphics.image.codec.tiff.TIFFImageDecoder.decodeAsRenderedImage(TIFFImageDecoder.java:85) ~[xmlgraphics-commons-2.3.jar:2.3]
ors-app    | 	at org.apache.xmlgraphics.image.codec.util.ImageDecoderImpl.decodeAsRaster(ImageDecoderImpl.java:136) ~[xmlgraphics-commons-2.3.jar:2.3]
ors-app    | 	at org.apache.xmlgraphics.image.codec.util.ImageDecoderImpl.decodeAsRaster(ImageDecoderImpl.java:122) ~[xmlgraphics-commons-2.3.jar:2.3]
ors-app    | 	at com.graphhopper.reader.dem.CGIARProvider.generateRasterFromFile(CGIARProvider.java:110) ~[graphhopper-core-v0.13.9.jar:?]
ors-app    | 	at com.graphhopper.reader.dem.AbstractTiffElevationProvider.getEle(AbstractTiffElevationProvider.java:133) ~[graphhopper-core-v0.13.9.jar:?]
ors-app    | 	at com.graphhopper.reader.dem.MultiSourceElevationProvider.getEle(MultiSourceElevationProvider.java:52) ~[graphhopper-core-v0.13.9.jar:?]
ors-app    | 	at com.graphhopper.reader.osm.OSMReader.getElevation(OSMReader.java:715) ~[graphhopper-reader-osm-v0.13.9.jar:?]
ors-app    | 	at org.heigit.ors.routing.graphhopper.extensions.ORSOSMReader.getElevation(ORSOSMReader.java:433) ~[classes/:6.3.2]
ors-app    | 	at com.graphhopper.reader.osm.OSMReader.addNode(OSMReader.java:676) ~[graphhopper-reader-osm-v0.13.9.jar:?]
ors-app    | 	at com.graphhopper.reader.osm.OSMReader.processNode(OSMReader.java:641) ~[graphhopper-reader-osm-v0.13.9.jar:?]
ors-app    | 	at com.graphhopper.reader.osm.OSMReader.writeOsm2Graph(OSMReader.java:293) ~[graphhopper-reader-osm-v0.13.9.jar:?]
ors-app    | 	at com.graphhopper.reader.osm.OSMReader.readGraph(OSMReader.java:178) ~[graphhopper-reader-osm-v0.13.9.jar:?]
ors-app    | 	at com.graphhopper.GraphHopper.importData(GraphHopper.java:735) ~[graphhopper-core-v0.13.9.jar:?]
ors-app    | 	at com.graphhopper.GraphHopper.readData(GraphHopper.java:714) ~[graphhopper-core-v0.13.9.jar:?]
ors-app    | 	at com.graphhopper.GraphHopper.process(GraphHopper.java:701) ~[graphhopper-core-v0.13.9.jar:?]
ors-app    | 	at com.graphhopper.GraphHopper.importOrLoad(GraphHopper.java:680) ~[graphhopper-core-v0.13.9.jar:?]
ors-app    | 	at org.heigit.ors.routing.graphhopper.extensions.ORSGraphHopper.importOrLoad(ORSGraphHopper.java:159) ~[classes/:6.3.2]
ors-app    | 	at org.heigit.ors.routing.RoutingProfile.initGraphHopper(RoutingProfile.java:191) ~[classes/:6.3.2]
ors-app    | 	at org.heigit.ors.routing.RoutingProfile.<init>(RoutingProfile.java:135) ~[classes/:6.3.2]
ors-app    | 	at org.heigit.ors.routing.RoutingProfileLoader.call(RoutingProfileLoader.java:35) ~[classes/:6.3.2]
ors-app    | 	at org.heigit.ors.routing.RoutingProfileLoader.call(RoutingProfileLoader.java:21) ~[classes/:6.3.2]
ors-app    | 	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
ors-app    | 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
ors-app    | 	at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
ors-app    | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
ors-app    | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
ors-app    | 	... 1 more
ors-app    | 27 Dec 21:24:07 INFO [routing.RoutingProfileManager] - ====> Recycling garbage...
ors-app    | 27 Dec 21:24:07 INFO [routing.RoutingProfileManager] - Before:  Total - 1024 MB, Free - 940.83 MB, Max: 2 GB, Used - 83.17 MB
ors-app    | 27 Dec 21:24:07 INFO [routing.RoutingProfileManager] - After:  Total - 1024 MB, Free - 995.34 MB, Max: 2 GB, Used - 28.66 MB
ors-app    | 27 Dec 21:24:07 INFO [routing.RoutingProfileManager] - ========================================================================
ors-app    | 27 Dec 21:24:07 INFO [routing.RoutingProfileManager] - ====> Memory usage by profiles:
ors-app    | 27 Dec 21:24:07 INFO [routing.RoutingProfileManager] - Total: 0 B (0.0%)
ors-app    | 27 Dec 21:24:07 INFO [routing.RoutingProfileManager] - ========================================================================
    c
^CGracefully stopping... (press Ctrl+C again to force)
```
---
#### Here's what I was expecting

It to start normally with no errors
---

**Comment by mshvarts** [comment]
@takb  ? can you help me figure out what is wrong? I don't see other people having this issue. i must be during something wrong with docker? I never used this service before

**Comment by leontodd** [comment]
I just had this same problem - looks like the default elevation provider's site is down.

See https://github.com/GIScience/openrouteservice/issues/839#issuecomment-744000100 for a fix that worked for me.

**Comment by mshvarts** [comment]
@leontodd Ah thank you! that seemed to fix the issue

**Comment by TheGreatRefrigerator** [comment]
Should be fixed in v6.3.3
Please reopen if this is still happening

**Comment by nickdbush** [comment]
I'm running into this exact issue with the v6.3.3 Docker image

**Comment by nilsnolde** [comment]
Can you try to build the image yourself? It seemed to work for https://github.com/GIScience/openrouteservice/issues/839#issuecomment-761636048

If that works but then 6.3.3 image from dockerhub doesn't, there's a problem on the dockerhub build..
